let messages = {"Maiming Strike":"致残突击",
"Blood Rush":"急进猛突",
"Voltaic Strike":"伏打电能",
"Primed Continuity":"持久力 PRIME",
"Transient Fortitude":"瞬时坚毅",
"Vitality":"生命力",
"Primed Flow":"川流不息 PRIME",
"Lightning Dash":"电光冲刺",
"Narrow Minded":"心志偏狭",
"Blind Rage":"盲怒",
"Steel Fiber":"金属纤维",
"Redirection":"蓄能重划",
"Energy Conversion":"能量转换",
"Continuity":"持久力",
"Augur Message":"预言 启示",
"Fleeting Expertise":"弹指瞬技",
"Streamline":"简化",
"Stretch":"延伸",
"Overextended":"过度延展",
"Power Drift":"力量窜升",
"Intensify":"聚精会神",
"Augur Secrets":"预言 神密",
"Corrosive Projection":"腐蚀投射",
"Coaction Drift":"协力窜升",
"Diamond Skin":"钻石皮肤",
"Enemy Sense":"敌人感应",
"Vigilante Pursuit":"私法 追踪",
"Rejuvenation":"返老还童",
"Physique":"体魄",
"Gladiator Resolve":"角斗士 决心",
"Loot Detector":"战利品探测器",
"Thief's Wit":"盗贼天赋",
"Endurance Drift":"坚忍窜升",
"Flow":"川流不息",
"Energy Siphon":"能量虹吸",
"Rapid Resilience":"极速复元",
"Vigor":"活力",
"Cunning Drift":"狡诈窜升",
"Maglev":"磁浮",
"Armored Agility":"灵活装甲",
"Intruder":"入侵者",
"Piercing Step":"穿刺步伐",
"Quick Thinking":"随机应变",
"Rifle Amp":"步枪增幅",
"Dead Eye":"死亡之眼",
"Streamlined Form":"流线外形",
"Steel Charge":"钢铁充能",
"Rush":"冲刺",
"Natural Talent":"天赋",
"Rage":"狂暴化",
"Constitution":"百折不挠",
"Handspring":"翻筋斗",
"Fast Deflection":"快速充能",
"Warm Coat":"保温服",
"Empowered Blades":"强化刀锋",
"Growing Power":"成长之力",
"Health Conversion":"生命转换",
"Brief Respite":"快速休整",
"Augur Reach":"预言 通灵",
"Stand United":"团结一致",
"Gladiator Aegis":"角斗士 圣盾",
"Reflex Guard":"反射防御",
"Undying Will":"不朽意志",
"Hunter Adrenaline":"猎人 肾上腺素",
"Shock Absorbers":"减震器",
"Antitoxin":"毒抗",
"Toxin Resistance":"毒素抵抗",
"Flame Repellent":"火焰防护",
"Agility Drift":"矫捷窜升",
"Lightning Rod":"避雷针",
"Insulation":"隔热",
"Aviator":"飞行员",
"Enemy Radar":"侦敌雷达",
"Stealth Drift":"匿踪窜升",
"Heavy Impact":"震地冲击",
"Fortitude":"不屈不挠",
"Sure Footed":"顶天立地",
"Pain Threshold":"痛苦阈值",
"Master Thief":"盗贼大师",
"Infested Impedance":"感染者阻抗",
"EMP Aura":"电磁脉冲场",
"Equilibrium":"均衡点",
"Retribution":"惩戒",
"Shield Disruption":"护盾瓦解",
"Augur Accord":"预言 协约",
"Vigilante Vigor":"私法 活力",
"Speed Drift":"速度窜升",
"Mobilize":"全面驱动",
"Ice Spring":"冰冷跃动",
"Toxic Flight":"剧毒飞腾",
"Rending Turn":"撕裂翻转",
"Battering Maneuver":"机动冲撞",
"Firewalker":"火焰行者",
"Patagium":"翼膜",
"Gladiator Finesse":"角斗士 灵巧",
"Pistol Scavenger":"手枪弹药搜集者",
"Rifle Scavenger":"步枪弹药搜集者",
"Sniper Scavenger":"狙击枪弹药搜集者",
"Shotgun Scavenger":"霰弹枪弹药搜集者",
"Pistol Amp":"手枪增幅",
"Provoked":"激怒",
"Shotgun Amp":"霰弹枪增幅",
"Speed Holster":"快速切换",
"Reflection":"充能反弹",
"Duality":"二元性状",
"Resonating Quake":"共鸣地震",
"Chilling Globe":"冰封护罩",
"Calm & Frenzy":"冷静与疯狂",
"Chromatic Blade":"华彩刀剑",
"Titanic Rumbler":"巨大石者",
"Soul Survivor":"幸存生灵",
"Shield of Shadows":"幽影之护",
"Jet Stream":"急流",
"Hall of Malevolence":"恶怨厅",
"Despoil":"掠夺",
"Savior Decoy":"救星诱饵",
"Tectonic Fracture":"构造裂缝",
"Eternal War":"永恒战意",
"Vampire Leech":"汲能榨取",
"Funnel Clouds":"漏斗状云",
"Iron Vault":"神针腾跃",
"Fatal Teleport":"致命传送",
"Pilfering Swarm":"贪夺触角",
"Reinforcing Stomp":"践踏加固",
"Irradiating Disarm":"辐射缴械",
"Repelling Bastille":"驱逐力场",
"Neutron Star":"中子星爆",
"Elemental Sandstorm":"元素沙暴",
"Total Eclipse":"全蚀",
"Icy Avalanche":"冰冷雪崩",
"Phoenix Renewal":"凤凰新生",
"Piercing Roar":"刺骨战吼",
"Seeking Shuriken":"削甲手里剑",
"Path of Statues":"化像之道",
"Primal Rage":"原始暴怒",
"Antimatter Absorb":"反物质吸收",
"Assimilate":"同化",
"Peaceful Provocation":"和平挑衅",
"Hallowed Eruption":"圣域爆发",
"Staggering Shield":"失衡护盾",
"Freeze Force":"寒冰之力",
"Guided Effigy":"导路龙骸",
"Smoke Shadow":"庇护烟幕",
"Ballistic Bullseye":"弹道靶心",
"Vexing Retaliation":"怨怒报复",
"Fire Fright":"惊惧热浪",
"Smite Infusion":"惩击洗礼",
"Contagion Cloud":"感染毒雾",
"Pacifying Bolts":"抚慰之风",
"Safeguard Switch":"护卫传送",
"Shield Transference":"护盾转移",
"Negation Swarm":"抵消虫群",
"Swing Line":"摆荡钩索",
"Transistor Shield":"晶管屏障",
"Muzzle Flash":"枪口闪焰",
"Beguiling Lantern":"欺幻魔灯",
"Resonance":"残响共鸣",
"Savage Silence":"残酷无息",
"Perpetual Vortex":"永动旋涡",
"Everlasting Ward":"永恒之护",
"Surging Dash":"涌流突进",
"Divebomb Vortex":"涡卷俯冲",
"Chaos Sphere":"混乱领域",
"Infiltrate":"渗透",
"Ice Wave Impedance":"滞痕冰浪",
"Tidal Impunity":"潮汐涌净",
"Pyroclastic Flow":"火成碎流",
"Safeguard":"火绫守护",
"Cataclysmic Continuum":"灾变连连",
"Firequake":"烈焰爆震",
"Explosive Legerdemain":"爆炸戏法",
"Tesla Link":"特斯拉陷阱",
"Hysterical Assault":"狂化突击",
"Furious Javelin":"狂怒标枪",
"Fireball Frenzy":"狂热火球",
"Venom Dose":"猛毒附加",
"Pool of Life":"生命之池",
"Shocking Speed":"电击加速",
"Shock Trooper":"电击奇兵",
"Capacitance":"电容",
"Curative Undertow":"疗愈漩涡",
"Ore Gaze":"矿石凝视",
"Sonic Fracture":"破碎声波",
"Iron Shrapnel":"碎铁弹片",
"Magnetized Discharge":"磁吸释放",
"Hallowed Reckoning":"神圣清算",
"Piercing Navigator":"穿刺抛体",
"Mind Freak":"精神狂怒",
"Radiant Finish":"终结闪光",
"Afterburn":"续燃",
"Creeping Terrify":"缓动惊骇",
"Abating Link":"耗弱链接",
"Escape Velocity":"脱离速度",
"Corroding Barrage":"腐蚀弹幕",
"Regenerative Molt":"蜕化再生",
"Rift Torrent":"裂隙洪流",
"Greedy Pull":"贪婪吸引",
"Haven":"避难所",
"Ironclad Charge":"铁甲冲锋",
"Prolonged Paralysis":"长时瘫痪",
"Flash Accelerant":"闪耀助燃",
"Hushed Invisibility":"静谧无踪",
"Rising Storm":"风起云涌",
"Fracturing Crush":"高压粉碎",
"Primed Cryo Rounds":"低温弹头 PRIME",
"Primed Point Blank":"抵近射击 PRIME",
"Primed Bane of Corpus":"灭亡 CORPUS PRIME",
"Primed Bane of Grineer":"灭亡 GRINEER PRIME",
"Primed Bane of Infested":"灭亡 INFESTED PRIME",
"Primed Bane of Corrupted":"灭亡堕落者 PRIME",
"Primed Fast Hands":"爆发装填 PRIME",
"Primed Ravage":"破灭 PRIME",
"Full Contact":"全面接触",
"Critical Delay":"关键延迟",
"Frigid Blast":"冰冷疾风",
"Adhesive Blast":"凝胶爆破",
"Split Chamber":"分裂膛室",
"Accelerated Blast":"加速冲击",
"Kinetic Ricochet":"动力回弹",
"Vile Acceleration":"卑劣加速",
"Metal Auger":"合金钻头",
"Hell's Chamber":"地狱弹膛",
"Lock and Load":"填弹上膛",
"Fanged Fusillade":"尖牙连射",
"Vital Sense":"弱点感应",
"Gun Glide":"恒稳枪杆",
"Vicious Spread":"恶性扩散",
"Sweeping Serration":"扫荡锯齿",
"Neutralizing Justice":"抵消正义",
"Shred":"撕裂",
"Scattered Justice":"散射正义",
"Tactical Reload":"机动装填",
"Vile Precision":"极恶精准",
"Rifle Ammo Mutation":"步枪弹药转换",
"Toxic Barrage":"毒素弹幕",
"Argon Scope":"氩晶瞄具",
"Lasting Purity":"永恒纯净",
"Tainted Shell":"污秽弹药",
"Double-Barrel Drift":"游离双管",
"Chilling Reload":"激冷装填",
"Combustion Beam":"灼热光束",
"Scattering Inferno":"炼狱轰击",
"Blaze":"烈焰",
"Firestorm":"烈焰风暴",
"Entropy Burst":"熵数爆发",
"Seeking Fury":"狂暴追猎",
"Narrow Barrel":"狭窄枪膛",
"Hunter Track":"猎人 追踪",
"Shell Shock":"电冲弹药",
"Voltage Sequence":"电压数列",
"Rime Rounds":"白霜弹头",
"Ravage":"破灭",
"Shattering Justice":"破碎正义",
"Breach Loader":"破裂填装",
"Vigilante Offense":"私法 侵犯",
"Vigilante Supplies":"私法 补给",
"Stabilizer":"稳定",
"Piercing Caliber":"穿甲口径",
"Seeking Force":"穿透力",
"Arrow Mutation":"箭矢转换",
"Spring-Loaded Broadhead":"簧压猎箭",
"Tether Grenades":"系绳榴弹",
"Nano-Applicator":"纳米涂覆",
"Disarming Purity":"缴械纯净",
"Depleted Reload":"耗竭装填",
"Tainted Mag":"腐败弹匣",
"Deadly Sequence":"致命数列",
"Malignant Force":"致命火力",
"Frail Momentum":"虚弱动能",
"Burdened Magazine":"过载弹匣",
"Crash Course":"连续冲击",
"Flux Overdrive":"通量射线步枪超载",
"Heavy Caliber":"重口径",
"Hammer Shot":"重锤射击",
"Wildfire":"野火",
"Thermite Rounds":"铝热焊弹",
"Target Acquired":"锁定目标",
"Gilded Truth":"镀金真相",
"Critical Deceleration":"降速暴击",
"Thunderbolt":"雷火",
"Shotgun Ammo Mutation":"霰弹枪弹药转换",
"High Voltage":"高压电流",
"Contagious Spread":"传染蔓延",
"Cryo Rounds":"低温弹头",
"Charged Shell":"充电弹头",
"Cleanse Corpus":"净化CORPUS",
"Cleanse Grineer":"净化GRINEER",
"Cleanse Infested":"净化INFESTED",
"Cleanse Corrupted":"净化堕落者",
"Sinister Reach":"凶恶延伸",
"Guided Ordinance":"制导弹药",
"Shell Compression":"压缩弹药",
"Hellfire":"地狱火",
"Nightwatch Napalm":"夜巡燃烧弹",
"Silent Battery":"寂静炮组",
"Bladed Rounds":"尖刃弹头",
"Fomorian Accelerant":"巨人促进剂",
"Broad Eye":"广域之视",
"Chilling Grasp":"急冻控场",
"Tactical Pump":"战术上膛",
"Point Blank":"抵近射击",
"Stormbringer":"暴风使者",
"Agile Aim":"机动瞄准",
"Terminal Velocity":"极限速度",
"Rifle Aptitude":"步枪才能",
"Infected Clip":"污染弹匣",
"Bane of Corpus":"灭亡CORPUS",
"Bane of Grineer":"灭亡GRINEER",
"Bane of Infested":"灭亡INFESTED",
"Bane Of Corrupted":"灭亡堕落者",
"Speed Trigger":"灵敏扳机",
"Incendiary Coat":"燃烧外壳",
"Hunter Munitions":"猎人 战备",
"Vigilante Fervor":"私法 热诚",
"Spring-Loaded Chamber":"簧压膛室",
"Soft Hands":"精湛快手",
"Overview":"综观全局",
"Serration":"膛线",
"Fatal Acceleration":"致死加速",
"Charged Chamber":"蓄力装填",
"Shotgun Spazz":"表演时间",
"Repeater Clip":"转轮弹匣",
"Twitch":"迅速抽换",
"Shotgun Savvy":"通晓霰弹枪",
"Snap Shot":"速射",
"Acid Shells":"酸性弹药",
"Laser Sight":"雷射瞄具",
"Ammo Stock":"霰弹扩充",
"Eagle Eye":"鹰眼",
"Disruptor":"冲击干扰",
"Magazine Warp":"弹匣增幅",
"Ammo Drum":"弹鼓",
"Lingering Torment":"恒久折磨",
"Continuous Misery":"无尽苦难",
"Hush":"消音器",
"Fast Hands":"爆发装填",
"Shrapnel Shot":"破片射击",
"Rupture":"破裂",
"Vigilante Armaments":"私法 军备",
"Piercing Hit":"穿甲伤害",
"Flechette":"箭型弹头",
"Shredder":"粉碎器",
"Point Strike":"致命一击",
"Catalyzer Link":"触媒连动",
"Sawtooth Clip":"锯齿弹链",
"Blunderbuss":"雷筒",
"Primed Slip Magazine":"串联弹匣 PRIME",
"Primed Target Cracker":"弱点专精 PRIME",
"Primed Pistol Gambit":"手枪精通 PRIME",
"Primed Heated Charge":"火焰装填 PRIME",
"Anemic Agility":"乏能迅敏",
"Eroding Blight":"侵蚀毁坏",
"Ice Storm":"冰风暴",
"Concealed Explosives":"内置炸药",
"Creeping Bullseye":"匍匐靶心",
"Sequence Burn":"延烧数列",
"Pressurized Magazine":"增压弹匣",
"Eject Magazine":"弹匣置换",
"Seeker":"弹头导引",
"Barrel Diffusion":"弹头扩散",
"Pummel":"强力猛击",
"Tainted Clip":"感染弹匣",
"Stunning Speed":"慑人神速",
"Pistol Ammo Mutation":"手枪弹药转换",
"Bore":"枪膛",
"Toxic Sequence":"毒素数列",
"Strafing Slide":"滑行扫射",
"Scorch":"灼痕焦点",
"Thermagnetic Shells":"热磁弹药",
"Entropy Spike":"熵数尖钉",
"Fulmination":"猛烈爆发",
"Jolt":"电流震击",
"Pistol Pestilence":"瘟疫手枪",
"Stockpiled Blight":"积存毁坏",
"Steady Hands":"稳定枪手",
"Hollow Point":"空尖弹",
"Winds of Purity":"纯净之风",
"Frostbite":"结霜侵蚀",
"Lethal Torrent":"致命洪流",
"Maim":"致残枪弹",
"Stinging Truth":"过激真相",
"Magnum Force":"重装火力",
"Augur Seeker":"预言 探求",
"Embedded Catalyzer":"内置触媒",
"Sure Shot":"准确射手",
"Razor Shot":"剃刀射击",
"Reflex Draw":"反射拔枪",
"Targeting Subsystem":"定位辅助",
"Sharpened Bullets":"尖锐子弹",
"Target Cracker":"弱点专精",
"No Return":"有去无回",
"Ruinous Extension":"毁灭扩展",
"Deep Freeze":"深层冷冻",
"Heated Charge":"火焰装填",
"Pathogen Rounds":"病原弹头",
"Convulsion":"痉挛",
"Gunslinger":"神枪手",
"Air Recon":"空中侦察",
"Lethal Momentum":"致命动量",
"Spry Sights":"迅敏视觉",
"Hawk Eye":"隼目",
"Concussion Rounds":"震荡弹头",
"Expel Corpus":"驱逐CORPUS",
"Expel Grineer":"驱逐GRINEER",
"Expel Infested":"驱逐INFESTED",
"Expel Corrupted":"驱逐堕落者",
"Hornet Strike":"黄蜂蛰刺",
"Slip Magazine":"串联弹匣",
"Trick Mag":"戏法增幅",
"Pistol Gambit":"手枪精通",
"Quickdraw":"持续火力",
"Perpetual Agony":"永恒苦痛",
"Suppress":"消音",
"Hydraulic Crosshairs":"液压准心",
"Augur Pact":"预言 契约",
"Primed Reach":"剑风 PRIME",
"Primed Pressure Point":"压迫点 PRIME",
"Primed Fever Strike":"热病打击 PRIME",
"Primed Fury":"狂暴 PRIME",
"Primed Heavy Trauma":"重创 PRIME",
"Bright Purity":"光明纯净",
"Collision Force":"冲击巨力",
"Virulent Scourge":"剧毒灾害",
"Quickening":"加速",
"Avenging Truth":"复仇真相",
"Power Throw":"奋力一掷",
"Guardian Derision":"奚落守护",
"Condition Overload":"异况超量",
"Rending Strike":"撕裂打击",
"Whirlwind":"旋风",
"Justice Blades":"正义刀锋",
"Gleaming Blight":"毁坏微光",
"Toxic Blight":"毁坏毒素",
"Healing Return":"治愈归复",
"Drifting Contact":"漂移接触",
"Entropy Detonation":"熵数起爆",
"Volcanic Edge":"爆裂刀刃",
"Berserker":"狂战士",
"Life Strike":"生命打击",
"Blade of Truth":"真相之刃",
"Sundering Strike":"破甲",
"Spring-Loaded Blade":"簧压刀刃",
"Focus Energy":"聚焦能量",
"Energy Channel":"能量导引",
"Spoiled Strike":"腐坏打击",
"Covert Lethality":"致命匿杀",
"Vicious Frost":"蚀骨寒霜",
"Auger Strike":"螺钻打击",
"Gladiator Vice":"角斗士 钳制",
"Buzz Kill":"败兴虐杀",
"Corrupt Charge":"邪恶蓄力",
"Heavy Trauma":"重创",
"Jagged Edge":"锯刃",
"Static Discharge":"静电释放",
"Entropy Flight":"飞逝熵数",
"Killing Blow":"一击必杀",
"Weeping Wounds":"创口溃烂",
"North Wind":"北风",
"Reflex Coil":"增幅线圈",
"Relentless Combination":"残酷组合",
"Smite Corpus":"毁灭CORPUS",
"Smite Grineer":"毁灭GRINEER",
"Smite Infested":"毁灭INFESTED",
"Smite Corrupted":"毁灭堕落者",
"Vulcan Blitz":"火神闪击",
"Fever Strike":"热病打击",
"Molten Impact":"熔岩冲击",
"Fury":"狂暴",
"Hunter's Bonesaw":"猎人骨锯",
"Shocking Touch":"电击触点",
"Electromagnetic Shielding":"电磁屏障",
"Finishing Touch":"画龙点睛",
"Rift Strike":"裂缝打击",
"Gladiator Might":"角斗士 威猛",
"Dispatch Overdrive":"超速击杀",
"Enduring Affliction":"长时苦难",
"Seismic Wave":"震波",
"Enduring Strike":"不朽打击",
"Pressure Point":"压迫点",
"Rebound":"弹跳",
"Quick Return":"快速收回",
"True Steel":"斩铁",
"Lasting Sting":"未完之刺",
"Body Count":"杀伤计数",
"Blocking":"格挡",
"True Punishment":"真实惩罚",
"Shattering Impact":"碎裂冲击",
"Organ Shatter":"肢解",
"Gladiator Rush":"角斗士 猛突",
"Focused Defense":"重点防御",
"Melee Prowess":"非凡技巧",
"Slicing Feathers":"割裂羽翼",
"Bullet Dance":"刀锋弹舞",
"Crossing Snakes":"双蛇牙突",
"Twirling Spire":"回转尖峰",
"Vengeful Revenant":"复仇亡灵",
"Flailing Branch":"多流抽击",
"Four Riders":"天启异象",
"Pointed Wind":"尖锐之风",
"Cleaving Whirlwind":"弧刃回天",
"Gleaming Talon":"微光利爪",
"Malicious Raptor":"恶毒猛禽",
"Astral Twilight":"星界微光",
"Crushing Ruin":"月落乌啼",
"Vermilion Storm":"朱红暴风",
"Decisive Judgement":"果断裁决",
"High Noon":"正午",
"Brutal Tide":"残暴浪潮",
"Gaia's Tragedy":"母神悲歌",
"Coiling Viper":"毒蛇螺旋",
"Vulpine Mask":"狡狐诈面",
"Gnashing Payara":"狼鱼咬咬",
"Swooping Falcon":"猎鹰俯击",
"Tempo Royale":"皇家节奏",
"Tranquil Cleave":"秋风落叶",
"Defiled Snapdragon":"积秽骁龙",
"Stalking Fan":"缠旋风切",
"Sovereign Outcast":"至尊浪人",
"Stinging Thorn":"蛰刺狂棘",
"Bleeding Willow":"血色万柳",
"Crimson Dervish":"赤红狂舞",
"Iron Phoenix":"钢铁凤凰",
"Carving Mantis":"雕斩螳螂",
"Seismic Palm":"震撼冲拳",
"Cyclone Kraken":"飓风海怪",
"Shattering Storm":"云暴山碎",
"Grim Fury":"冷面狂怒",
"Sundering Weave":"分裂编织",
"Clashing Forest":"巨林冲击",
"Rending Crane":"撕裂鹤击",
"Reaping Spiral":"收割螺旋",
"Spinning Needle":"旋压刺针",
"Swirling Tiger":"旋风虎击",
"Blind Justice":"无明制裁",
"Final Harbinger":"最终先驱",
"Sinking Talon":"沉没之爪",
"Atlantis Vulcan":"深渊之火",
"Burning Wasp":"炙热黄蜂",
"Fracturing Wind":"破碎之风",
"Gemini Cross":"纵横双子",
"Eleventh Storm":"终焉风暴",
"Homing Fang":"连牙追袭",
"Primed Morphic Transformer":"非晶变压器 PRIME",
"Afterburner":"加力燃烧",
"Kinetic Diversion":"动力转移",
"Cold Snap":"寒流来袭",
"System Reroute":"系统重划",
"Energy Field":"能量力场",
"Hyperion Thrusters":"超越推进",
"Morphic Transformer":"非晶变压器",
"Efficient Transferral":"高效传输",
"Superior Defenses":"卓越防御",
"Enhanced Durability":"耐久强化",
"Energy Amplifier":"能量扩散",
"Auxiliary Power":"辅助动力",
"Argon Plating":"氩晶装甲",
"Energy Inversion":"能量转化",
"Hollowed Bullets":"中空子弹",
"Dual Rounds":"双重弹头",
"Comet Blast":"彗星爆发",
"Magma Chamber":"熔岩弹膛",
"Quasar Drill":"类星钻体",
"Automatic Trigger":"自动扳机",
"Zodiac Shred":"黄道碎裂",
"Shell Rush":"填弹加速",
"Electrified Barrel":"带电枪管",
"Modified Munitions":"弹药改良",
"Venomous Clip":"恶毒弹匣",
"Polar Magazine":"极地弹仓",
"Combustion Rounds":"燃烧弹头",
"Rubedo-Lined Barrel":"红晶枪管",
"Magazine Extension":"扩充弹匣",
"Parallax Scope":"视差瞄具",
"Nebula Bore":"星云钻孔",
"Astral Slash":"星体切砍",
"Astral Autopsy":"星界剖解",
"Meteor Crash":"流星撞击",
"Searing Steel":"炽燃钢铁",
"Glacial Edge":"冰冷刃缘",
"Poisonous Sting":"剧毒螯刺",
"Blazing Steel":"炽烈坚刃",
"Furor":"狂怒",
"Galvanized Blade":"通电刀刃",
"Cutting Edge":"切割刃缘",
"Extend":"延展",
"Tempered Blade":"强化刀片",
"Sudden Impact":"瞬间冲击",
"Bleeding Edge":"血色刃缘",
"Primed Regen":"重生 PRIME",
"Coolant Leak":"冷却液外泄",
"Animal Instinct":"动物本能",
"Sanctuary":"守护光罩",
"Detect Vulnerability":"弱点侦测",
"Shield Charger":"护盾充能",
"Looter":"搜刮者",
"Sacrifice":"牺牲",
"Self Destruct":"自爆",
"Fired Up":"过热射击",
"Accelerated Deflection":"加速充能",
"Medi-Ray":"医疗射线",
"Spare Parts":"残余",
"Crowd Dispersion":"人群驱散",
"Investigator":"侦察",
"Molecular Conversion":"分子转化",
"Striker":"前锋",
"Vacuum":"吸取",
"Revenge":"复仇",
"Guardian":"守护者",
"Ghost":"幽灵",
"Ammo Case":"弹药储转箱",
"Warrior":"战士",
"Enhanced Vitality":"构造强化",
"Vaporize":"汽化",
"Electro Pulse":"电光脉冲",
"Arc Coil":"电弧线圈",
"Targeting Receptor":"目标感应",
"Swift Deth":"瞬杀",
"Calculated Shot":"精算射击",
"Calculated Redirection":"精算蓄能",
"Fatal Attraction":"致命诱惑",
"Thumper":"重击者",
"Retarget":"重定向",
"Regen":"重生",
"Protect":"保护",
"Ferocity":"凶恶终结",
"Reflect":"反射",
"Bite":"咬碎",
"Neutralize":"啃咬压制",
"Howl":"嚎声",
"Medi-Pet Kit":"宠物治疗套件",
"Charm":"招福",
"Dig":"挖掘",
"Hunt":"狩猎",
"Hunter Command":"猎人 命令",
"Cat's Eye":"猫眼",
"Unleashed":"释放",
"Savagery":"野蛮压制",
"Stalk":"隐秘追踪",
"Mischief":"顽皮",
"Territorial Aggression":"侵略领土",
"Sense Danger":"危机感知",
"Shelter":"庇护",
"Hastened Deflection":"急速偏斜",
"Link Armor":"护甲连结",
"Swipe":"挥击",
"Maul":"捶击",
"Hunter Synergy":"猎人 协力",
"Pounce":"猛扑",
"Link Health":"生命值连结",
"Sharpened Claws":"磨锋之爪",
"Retrieve":"嗅索取物",
"Loyal Companion":"忠实搭档",
"Scavenge":"搜集",
"Hunter Recovery":"猎人 复元",
"Pack Leader":"领袖",
"Proboscis":"长吻",
"Dex Dakra":"DEX 达克拉双剑",
"MK1-Bo":"MK1-玻之武杖",
"Endura":"三叶坚韧",
"Dual Zoren":"佐伦双斧",
"Nikana":"侍刃",
"Nikana Prime":"侍刃 PRIME",
"Secura Lecta":"保障 勒克塔",
"Cronus":"克洛诺斯",
"Krohkur":"克鲁古尔",
"Guandao":"关刀",
"Gunsen":"军扇",
"Venka":"凯旋之爪",
"Venka Prime":"凯旋之爪 PRIME",
"Karyst":"凯洛斯特",
"Scindo":"分裂斩斧",
"Scindo Prime":"分裂斩斧 PRIME",
"Volnus":"创伤",
"Gazal Machete":"加扎勒反曲刀",
"Vaykor Sydon":"勇气 恶龙",
"Lecta":"勒克塔",
"Amphis":"双头蛇",
"Twin Krohkur":"双子克鲁古尔",
"Twin Basolk":"双子巴萨克",
"Dual Kamas":"双短柄战镰",
"Dual Kamas Prime":"双短柄战镰 PRIME",
"Shaku":"双节尺棍",
"Halikar":"哈利卡",
"Jat Kittag":"喷射战锤",
"Jat Kusar":"喷射锁镰",
"Sancti Magistar":"圣洁 执法者",
"Anku":"夺魂死神",
"Obex":"奥比克斯",
"Scoliac":"嵴椎节鞭",
"Sheev":"希芙",
"Silva & Aegis":"席瓦 & 神盾",
"Silva & Aegis Prime":"席瓦 & 神盾 PRIME",
"Furax":"弗拉克斯",
"Arca Titron":"弧电振子锤",
"Kesheg":"怯薛",
"Dual Ichor":"恶脓双斧",
"Sydon":"恶龙",
"Lacera":"悲痛之刃",
"Hate":"憎恨",
"War":"战争之剑",
"Glaive Prime":"战刃 PRIME",
"Magistar":"执法者",
"Destreza":"技巧之剑",
"Tipedo":"提佩多",
"Reaper Prime":"收割者 PRIME",
"Redeemer":"救赎者",
"Dual Cleavers":"斩肉双刀",
"Prova":"普罗沃",
"Prova Vandal":"普罗沃 破坏者",
"Dark Split-Sword":"暗黑分合剑",
"Dark Sword":"暗黑长剑",
"Synoid Heliocor":"枢议 赫利俄光锤",
"Gram":"格拉姆",
"Prisma Obex":"棱晶 奥比克斯",
"Prisma Dual Cleavers":"棱晶 斩肉双刀",
"Prisma Skana":"棱晶空刃",
"Orthos":"欧特鲁斯",
"Orthos Prime":"欧特鲁斯 PRIME",
"Ohma":"欧玛",
"Nami Solo":"海波单剑",
"Nami Skyla":"海波斯库拉对剑",
"Nami Skyla Prime":"海波斯库拉对剑 PRIME",
"Orvius":"灵枢",
"Heat Dagger":"烈焰短剑",
"Mios":"牝狮神",
"Fang":"狼牙",
"Fang Prime":"狼牙 PRIME",
"Bo":"玻之武杖",
"Bo Prime":"玻之武杖 PRIME",
"Ankyros":"甲龙双拳",
"Ankyros Prime":"甲龙双拳 PRIME",
"Serro":"电能斩锯",
"Lesion":"病变",
"Kronen":"皇家拐刃",
"Kama":"短柄战镰",
"Broken Scepter":"破损珽杖",
"Broken-War":"破碎的战争之剑",
"Kogake":"科加基",
"Kogake Prime":"科加基 PRIME",
"Skana":"空刃",
"Skana Prime":"空刃 PRIME",
"Dual Skana":"空刃双刀",
"Kestrel":"红隼",
"Telos Boltace":"终极 螺钉拐刃",
"Rakta Dark Dagger":"绯红 暗黑匕首",
"Okina":"翁",
"Ether Sword":"苍穹之剑",
"Ether Daggers":"苍穹匕首",
"Dual Ether":"苍穹双剑",
"Ether Reaper":"苍穹死神",
"Hirudo":"蚂蝗",
"Sarpa":"蛇刃",
"Jaw Sword":"蛇颚刀",
"Tonbo":"蜻蛉薙",
"Boltace":"螺钉拐刃",
"Cerata":"裸鳃刃",
"Sibear":"西伯利亚冰锤",
"Ack & Brunt":"认知&冲击",
"Heliocor":"赫利俄光锤",
"Dakra Prime":"达克拉 PRIME",
"Galatine":"迦伦提恩",
"Galatine Prime":"迦伦提恩 PRIME",
"Fragor":"重击巨锤",
"Fragor Prime":"重击巨锤 PRIME",
"Tekko":"铁钩手甲",
"Dual Raza":"锋月双斧",
"Ripkas":"锐卡斯",
"Atterax":"阿特拉克斯",
"Ninkondi":"降灵追猎者",
"Machete":"马谢特砍刀",
"Machete Wraith":"马谢特砍刀 亡魂",
"Pangolin Sword":"鲮鲤剑",
"Cassowar":"鹤鸵长戟",
"Dragon Nikana":"龙之侍刃",
"Centaur":"半人马",
"Onorix":"奥努里克斯",
"Rathbone":"拉斯波恩",
"Prisma Veritux":"棱晶 真理巨剑",
"Veritux":"真理巨剑",
"Agkuza":"驯象钩刃",
"Kaszas":"死亡使徒",
"Dark Dagger":"暗黑匕首",
"Dual Heat Swords":"烈焰双剑",
"Ceramic Dagger":"陶瓷匕首",
"Plasma Sword":"等离子长剑",
"Glaive":"战刃",
"Mire":"米尔",
"Heat Sword":"烈焰长剑",
"Furax Wraith":"弗拉克斯 亡魂",
"Caustacyst":"灼蚀变体镰",
"Sigma & Octantis":"西格玛 & 南极座",
"Knux":"克纳克斯",
"ZAW":"ZAW",
"Dex Sybaris":"DEX 席芭莉丝",
"MK1-Braton":"MK1-布莱顿",
"MK1-Paris":"MK1-帕里斯",
"MK1-Strun":"MK1-斯特朗",
"Ignis":"伊格尼斯",
"Ignis Wraith":"伊格尼斯 亡魂",
"Burston":"伯斯顿",
"Burston Prime":"伯斯顿 PRIME",
"Secura Penta":"保障 潘塔",
"Lanka":"兰卡",
"Glaxion":"冷冻光束步枪",
"Vaykor Hek":"勇气 海克",
"Karak":"卡拉克",
"Karak Wraith":"卡拉克 亡魂",
"Tenora":"双簧管",
"Harpak":"哈帕克",
"Phage":"噬菌者",
"Sancti Tigris":"圣洁 猛虎",
"Daikyu":"大久和弓",
"Quartakk":"夸塔克",
"Opticor":"奥堤克光子枪",
"Vectis":"守望者",
"Vectis Prime":"守望者 PRIME",
"Amprex":"安培克斯",
"Kohm":"寇恩热能枪",
"Convectrix":"导热聚焦枪",
"Buzlok":"巴兹火枪",
"Braton":"布莱顿",
"Braton Prime":"布莱顿 PRIME",
"Paris":"帕里斯",
"Braton Vandal":"布莱顿 破坏者",
"Paris Prime":"帕里斯 PRIME",
"Sybaris":"席芭莉丝",
"Sybaris Prime":"席芭莉丝 PRIME",
"Mutalist Cernos":"异融 西诺斯",
"Mutalist Quanta":"异融量子枪",
"Arca Plasmor":"弧电离子枪",
"Tonkor":"征服榴炮",
"Dera":"德拉",
"Dera Vandal":"德拉 破坏者",
"Dread":"恐惧",
"Torid":"托里德",
"Latron":"拉特昂",
"Latron Prime":"拉特昂 PRIME",
"Latron Wraith":"拉特昂 亡魂",
"Stradavar":"斯特拉迪瓦",
"Strun":"斯特朗",
"Strun Wraith":"斯特朗 亡魂",
"Soma":"月神",
"Soma Prime":"月神 PRIME",
"Synoid Simulor":"枢议 重力奇点拟成枪",
"Prisma Tetra":"棱晶 特拉",
"Prisma Gorgon":"棱晶 蛇发女妖",
"Prisma Grakata":"棱晶 葛拉卡达",
"Lenz":"楞次弓",
"Argonak":"氩格纳克",
"Zarr":"沙皇",
"Hek":"海克",
"Penta":"潘塔",
"Javlok":"燃焰标枪",
"Tetra":"特拉",
"Tiberon":"狂鲨",
"Snipetron":"狙击特昂",
"Snipetron Vandal":"狙击特昂 破坏者",
"Panthera":"猎豹",
"Tigris":"猛虎",
"Tigris Prime":"猛虎 PRIME",
"Astilla":"碎裂者",
"Scourge":"祸根",
"Corinth":"科林斯",
"Miter":"米特尔",
"Telos Boltor":"终极 螺钉步枪",
"Rubico":"绝路",
"Rakta Cernos":"绯红 西诺斯",
"Baza":"苍鹰",
"Supra":"苏普拉",
"Grinlok":"葛恩火枪",
"Grakata":"葛拉卡达",
"Gorgon":"蛇发女妖",
"Gorgon Wraith":"蛇发女妖 亡魂",
"Boltor Prime":"螺钉步枪 PRIME",
"Hema":"血肢",
"Cernos":"西诺斯",
"Cernos Prime":"西诺斯 PRIME",
"Zhuge":"诸葛连弩",
"Flux Rifle":"通量射线步枪",
"Simulor":"重力奇点拟成枪",
"Boar":"野猪",
"Boar Prime":"野猪 PRIME",
"Quanta":"量子切割器",
"Quanta Vandal":"量子切割器 破坏者",
"Vulkar":"金工火神",
"Vulkar Wraith":"金工火神 亡魂",
"Ferrox":"铁晶磁轨炮",
"Attica":"阿提卡",
"Paracyst":"附肢寄生者",
"Hind":"雌鹿",
"Ogris":"食人女魔",
"Sobek":"鳄神",
"Drakgoon":"龙骑兵",
"Dual Decurion":"什长双枪",
"Imperator":"凯旋将军",
"Imperator Vandal":"凯旋将军 破坏者",
"Cyngas":"合成燃气炮",
"Fluctus":"巨浪",
"Velocitus":"极速电磁步枪",
"Phaedra":"菲德菈",
"Corvas":"黑鸦",
"Boltor":"螺钉步枪",
"Synapse":"突触生化枪",
"Supra Vandal":"苏普拉 破坏者",
"Grattler":"葛拉特勒",
"Dex Furis":"DEX 盗贼双枪",
"MK1-Furis":"MK1-盗贼",
"MK1-Kunai":"MK1-苦无",
"Knell":"丧钟",
"Secura Dual Cestra":"保障 锡斯特双枪",
"Spectra":"光谱切割器",
"Nukor":"努寇微波枪",
"Vaykor Marelok":"勇气 玛瑞火枪",
"Kraken":"北海巨妖",
"Atomos":"原子矿融炮",
"Twin Kohmak":"双子寇恩霰机枪",
"Twin Gremlins":"双子小精灵",
"Twin Rogga":"双子罗格",
"Twin Grakata":"双子葛拉卡达",
"Twin Vipers":"双子蝰蛇",
"Wraith Twin Vipers":"双子蝰蛇 亡魂",
"Stubba":"史度巴",
"Akstiletto":"史提托双枪",
"Akstiletto Prime":"史提托双枪 PRIME",
"Stug":"史特克",
"Gammacor":"咖玛腕甲枪",
"Tysis":"啐沫者",
"Sancti Castanas":"圣洁 雷爆信标",
"Embolist":"安柏勒斯",
"Angstrum":"安格斯壮",
"Kohmak":"寇恩霰机枪",
"Brakk":"布拉克",
"Ballistica":"布里斯提卡",
"Ballistica Prime":"布里斯提卡 PRIME",
"Arca Scisco":"弧电探知者",
"Cycron":"循环离子枪",
"Detron":"德特昂",
"Euphona Prime":"悦音 PRIME",
"Pandero":"手鼓",
"Aklato":"拉托双枪",
"Azima":"方位角",
"Spira":"旋刃飞刀",
"Spira Prime":"旋刃飞刀 PRIME",
"Sicarus":"暗杀者",
"Sicarus Prime":"暗杀者 PRIME",
"Kulstar":"杀星",
"Synoid Gammacor":"枢议 咖玛腕甲枪",
"Prisma Angstrum":"棱晶 安格斯壮",
"Dual Toxocyst":"毒囊双枪",
"Zakti":"毒芽",
"Marelok":"玛瑞火枪",
"Vasto":"瓦斯托",
"Vasto Prime":"瓦斯托 PRIME",
"Akvasto":"瓦斯托双枪",
"Furis":"盗贼",
"Afuris":"盗贼双枪",
"Telos Akbolto":"终极 螺钉双枪",
"Despair":"绝望",
"Rakta Ballistica":"绯红 布里斯提卡",
"Pox":"脓痘",
"Kunai":"苦无",
"Detron Mara":"苦痛 德特昂",
"AkZani":"荒谬双枪",
"Viper":"蝰蛇",
"Viper Wraith":"蝰蛇 亡魂",
"Akbolto":"螺钉双枪",
"Akbolto Prime":"螺钉双枪 PRIME",
"Bolto":"螺钉手枪",
"AkJagara":"觉醒双枪",
"Sonicor":"超音波冲击枪",
"Aksomati":"轻灵月神双枪",
"Bronco":"野马",
"Bronco Prime":"野马 PRIME",
"Akbronco":"野马双枪",
"Akbronco Prime":"野马双枪 PRIME",
"Cestra":"锡斯特",
"Dual Cestra":"锡斯特双枪",
"Acrid":"阿克里德",
"Lex":"雷克斯",
"Lex Prime":"雷克斯 PRIME",
"Aklex":"雷克斯双枪",
"Aklex Prime":"雷克斯双枪 PRIME",
"Castanas":"雷爆信标",
"Staticor":"静电能量导引枪",
"Seer":"预言者",
"Hikou":"飞扬",
"Hikou Prime":"飞扬 PRIME",
"Pyrana":"食人鱼",
"Talons":"鹰爪",
"Magnus":"麦格努斯",
"Akmagnus":"麦格努斯双枪",
"Fusilai":"齐射玻刃",
"Lato":"拉托",
"Lato Prime":"拉托 PRIME",
"Lato Vandal":"拉托 破坏者",
"Zenistar":"天顶之星",
"Zenith":"天穹之顶",
"Deconstructor":"分离",
"Deconstructor Prime":"分离 PRIME",
"Sweeper":"扫除者",
"Sweeper Prime":"扫除者 PRIME",
"Deth Machine Rifle":"死亡机枪",
"Stinger":"毒刺",
"Laser Rifle":"激光步枪",
"Prime Laser Rifle":"激光步枪 PRIME",
"Burst Laser":"激光点发",
"Vulklok":"金工火枪",
"Artax":"阿塔克斯",
"Prisma Burst Laser":"棱晶 激光点发",
"Ferrite":"铁氧体",
"Nano Spores":"纳米孢子",
"Alloy Plate":"合金板",
"Salvage":"回收金属",
"Polymer Bundle":"聚合物束",
"Cryotic":"永冻晶矿",
"Circuits":"电路",
"Plastids":"生物质",
"Rubedo":"红化结晶",
"Argon Crystal":"氩结晶",
"Control Module":"控制模块",
"Gallium":"镓",
"Morphics":"非晶态合金",
"Neural Sensors":"神经传感器",
"Neurodes":"神经元",
"Orokin Cell":"OROKIN电池",
"Oxium":"奥席金属",
"Tellurium":"碲",
"Detonite Ampule":"爆燃安瓿",
"Fieldron Sample":"电磁力场装置样本",
"Mutagen Sample":"样本突变原",
"Coprun":"亚铜",
"Coprite Alloy":"亚铜合金",
"Devar":"兄弟之石",
"Esher Devar":"伊舍兄弟之石",
"Iradite":"伊莱体",
"Cuthol Tendrils":"克苏尔卷须",
"Karkina Antenna":"卡其那触须",
"Goopolla Spleen":"古泊拉脾脏",
"Mawfish Bones":"喉鱼骨骼",
"Synthula":"合成刺激质",
"Tralok Eyes":"塔洛鱼眼",
"Breath Of The Eidolon":"夜灵之息",
"Marquise Veridos":"女侯爵翠萤石",
"Nistlepod":"尼蒐荚",
"Cetus Wisp":"希图斯幽魂",
"Khut-Khut Venom Sac":"库特-库特毒囊",
"Kuaka Spinal Claw":"库阿卡脊爪",
"Mutalist Alad V Assassinate Key":"异融ALAD V刺杀钥匙",
"Radian Sentirum":"弧度心智晶核",
"Heart Nyth":"心形灵息石",
"Sentirum":"心智晶核",
"Mortus Horn":"摩图斯角",
"Charc Electroplax":"查克放电腺体",
"Nitain Extract":"泥炭萃取物",
"Tear Azurite":"泪滴形石青",
"Nyth":"灵息石",
"Pyrol":"炎晶",
"Pyrotic Alloy":"炎晶合金",
"Detonite Injector":"爆燃喷射器",
"Fieldron":"电磁力场装置",
"Mutagen Mass":"突变原聚合物",
"Azurite":"石青",
"Yogwun Stomach":"约格温鱼胃",
"Condroc Wing":"秃鹰翅膀",
"Crimzian":"绯红石",
"Veridos":"翠萤石",
"Grokdrul":"葛克度",
"Void Traces":"虚空光体",
"Norg Brain":"诺格鱼脑",
"Kuva":"赤毒",
"Auron":"金辉",
"Auroxium Alloy":"金辉合金",
"Fersteel Alloy":"钢化铁岩",
"Ferros":"铁岩",
"Murkray Liver":"阴暗鳐肝脏",
"Maprico":"马利可",
"Sharrac Teeth":"鲨客牙齿",
"Mawfish":"喉鱼",
"Charc Eel":"查克鳗",
"Khut-Khut":"库特-库特",
"Yogwun":"约格温",
"Mortus Lungfish":"摩图斯肺鱼",
"Goopolla":"古泊拉",
"Tralok":"塔洛",
"Sharrac":"鲨客",
"Karkina":"卡其那",
"Cuthol":"克苏尔",
"Murkray":"阴暗鳐",
"Norg":"诺格",
"Glappid":"盖拉佩德",
"Boot":"靴子",
"Nikana Prime Hilt":"侍刃 PRIME 握柄",
"Nikana Prime Blade":"侍刃 PRIME 刀刃",
"Nikana Prime Blueprint":"侍刃 PRIME 蓝图",
"Venka Prime Gauntlet":"凯旋之爪 PRIME 手套",
"Venka Prime Blades":"凯旋之爪 PRIME 爪刃",
"Venka Prime Blueprint":"凯旋之爪 PRIME 蓝图",
"Scindo Prime Blueprint":"分裂斩斧 PRIME 蓝图",
"Scindo Prime Blade":"分裂斩斧 PRIME 刀刃",
"Scindo Prime Handle":"分裂斩斧 PRIME 握柄",
"Dual Kamas Prime Blueprint":"双短柄战镰 PRIME 蓝图",
"Dual Kamas Prime Blade":"双短柄战镰 PRIME 刀刃",
"Dual Kamas Prime Handle":"双短柄战镰 PRIME 握柄",
"Sheev Blade":"希芙 刀刃",
"Sheev Heatsink":"希芙 散热器",
"Sheev Hilt":"希芙 握柄",
"Sheev Blueprint":"希芙 蓝图",
"Silva & Aegis Prime Blueprint":"席瓦 & 神盾 PRIME 蓝图",
"Silva & Aegis Prime Blade":"席瓦 & 神盾 PRIME 刀刃",
"Silva & Aegis Prime Guard":"席瓦 & 神盾 PRIME 护手",
"Silva & Aegis Prime Hilt":"席瓦 & 神盾 PRIME 握柄",
"Glaive Prime Blueprint":"战刃 PRIME 蓝图",
"Glaive Prime Disc":"战刃 PRIME 圆盘",
"Glaive Prime Blade":"战刃 PRIME 刀刃",
"Reaper Prime Blueprint":"收割者 PRIME 蓝图",
"Reaper Prime Blade":"收割者 PRIME 刀刃",
"Reaper Prime Handle":"收割者 PRIME 握柄",
"Orthos Prime Blueprint":"欧特鲁斯 PRIME 蓝图",
"Orthos Prime Blade":"欧特鲁斯 PRIME 刀刃",
"Orthos Prime Handle":"欧特鲁斯 PRIME 握柄",
"Nami Skyla Prime Blueprint":"海波斯库拉对剑 PRIME 蓝图",
"Nami Skyla Prime Blade":"海波斯库拉对剑 PRIME 刀刃",
"Nami Skyla Prime Handle":"海波斯库拉对剑 PRIME 握柄",
"Fang Prime Blade":"狼牙 PRIME 刀刃",
"Fang Prime Handle":"狼牙 PRIME 握柄",
"Fang Prime Blueprint":"狼牙 PRIME 蓝图",
"Bo Prime Ornament":"玻之武杖 PRIME 饰物",
"Bo Prime Handle":"玻之武杖 PRIME 握柄",
"Bo Prime Blueprint":"玻之武杖 PRIME 蓝图",
"Ankyros Prime Blade":"甲龙双拳 PRIME 刀刃",
"Ankyros Prime Gauntlet":"甲龙双拳 PRIME 拳套",
"Ankyros Prime Blueprint":"甲龙双拳 PRIME 蓝图",
"Kogake Prime Gauntlet":"科加基 PRIME 拳套",
"Kogake Prime Boot":"科加基 PRIME 靴子",
"Kogake Prime Blueprint":"科加基 PRIME 蓝图",
"Dakra Prime Blade":"达克拉 PRIME 刀刃",
"Dakra Prime Handle":"达克拉 PRIME 握柄",
"Dakra Prime Blueprint":"达克拉 PRIME 蓝图",
"Galatine Prime Blade":"迦伦提恩 PRIME 刀刃",
"Galatine Prime Handle":"迦伦提恩 PRIME 握柄",
"Galatine Prime Blueprint":"迦伦提恩 PRIME 蓝图",
"Fragor Prime Head":"重击巨锤 PRIME 锤头",
"Fragor Prime Handle":"重击巨锤 PRIME 握柄",
"Fragor Prime Blueprint":"重击巨锤 PRIME 蓝图",
"Centaur Blade":"半人马 刀刃",
"Centaur Aegis":"半人马 盾",
"Centaur Handle":"半人马 握柄",
"Onorix Blade":"奥努里克斯 刀刃",
"Onorix Handle":"奥努里克斯 握柄",
"Rathbone Head":"拉斯波恩 锤头",
"Rathbone Handle":"拉斯波恩 握柄",
"Agkuza Blade":"驯象钩刃 刀刃",
"Agkuza Handle":"驯象钩刃 握柄",
"Agkuza Guard":"驯象钩刃 护手",
"Kaszas Blade":"死亡使徒 刀刃",
"Kaszas Handle":"死亡使徒 握柄",
"Furax Wraith Blueprint":"弗拉克斯 亡魂 蓝图",
"Furax Wraith Left Gauntlet":"弗拉克斯亡魂 左拳套",
"Furax Wraith Right Gauntlet":"弗拉克斯亡魂 右拳套",
"Burston Prime Blueprint":"伯斯顿 PRIME 蓝图",
"Burston Prime Barrel":"伯斯顿 PRIME 枪管",
"Burston Prime Receiver":"伯斯顿 PRIME 枪机",
"Burston Prime Stock":"伯斯顿 PRIME 枪托",
"Karak Wraith Blueprint":"卡拉克 亡魂 蓝图",
"Karak Wraith Barrel":"卡拉克 亡魂 枪管",
"Karak Wraith Receiver":"卡拉克 亡魂 枪机",
"Karak Wraith Stock":"卡拉克 亡魂 枪托",
"Vectis Prime Blueprint":"守望者 PRIME 蓝图",
"Vectis Prime Barrel":"守望者 PRIME 枪管",
"Vectis Prime Receiver":"守望者 PRIME 枪机",
"Vectis Prime Stock":"守望者 PRIME 枪托",
"Braton Prime Blueprint":"布莱顿 PRIME 蓝图",
"Braton Prime Barrel":"布莱顿 PRIME 枪管",
"Braton Prime Receiver":"布莱顿 PRIME 枪机",
"Braton Prime Stock":"布莱顿 PRIME 枪托",
"Paris Prime Blueprint":"帕里斯 PRIME 蓝图",
"Paris Prime Upper Limb":"帕里斯 PRIME 上弓臂",
"Paris Prime Lower Limb":"帕里斯 PRIME 下弓臂",
"Paris Prime Grip":"帕里斯 PRIME 弓身",
"Paris Prime String":"帕里斯 PRIME 弓弦",
"Sybaris Prime Blueprint":"席芭莉丝 PRIME 蓝图",
"Sybaris Prime Barrel":"席芭莉丝 PRIME 枪管",
"Sybaris Prime Receiver":"席芭莉丝 PRIME 枪机",
"Sybaris Prime Stock":"席芭莉丝 PRIME 枪托",
"Dera Vandal Blueprint":"德拉 破坏者 蓝图",
"Dera Vandal Barrel":"德拉 破坏者 枪管",
"Dera Vandal Receiver":"德拉 破坏者 枪机",
"Dera Vandal Stock":"德拉 破坏者 枪托",
"Latron Prime Blueprint":"拉特昂 PRIME 蓝图",
"Latron Prime Barrel":"拉特昂 PRIME 枪管",
"Latron Prime Receiver":"拉特昂 PRIME 枪机",
"Latron Prime Stock":"拉特昂 PRIME 枪托",
"Latron Wraith Blueprint":"拉特昂 亡魂 蓝图",
"Latron Wraith Barrel":"拉特昂 亡魂 枪管",
"Latron Wraith Receiver":"拉特昂 亡魂 枪机",
"Latron Wraith Stock":"拉特昂 亡魂 枪托",
"Strun Wraith Blueprint":"斯特朗 亡魂 蓝图",
"Strun Wraith Barrel":"斯特朗 亡魂 枪管",
"Strun Wraith Receiver":"斯特朗 亡魂 枪机",
"Strun Wraith Stock":"斯特朗 亡魂 枪托",
"Soma Prime Blueprint":"月神 PRIME 蓝图",
"Soma Prime Barrel":"月神 PRIME 枪管",
"Soma Prime Receiver":"月神 PRIME 枪机",
"Soma Prime Stock":"月神 PRIME 枪托",
"Snipetron Vandal Blueprint":"狙击特昂 破坏者 蓝图",
"Snipetron Vandal Barrel":"狙击特昂 破坏者 枪管",
"Snipetron Vandal Receiver":"狙击特昂 破坏者 枪机",
"Snipetron Vandal Stock":"狙击特昂 破坏者 枪托",
"Tigris Prime Blueprint":"猛虎 PRIME 蓝图",
"Tigris Prime Barrel":"猛虎 PRIME 枪管",
"Tigris Prime Receiver":"猛虎 PRIME 枪机",
"Tigris Prime Stock":"猛虎 PRIME 枪托",
"Gorgon Wraith Barrel":"蛇发女妖 亡魂 枪管",
"Gorgon Wraith Receiver":"蛇发女妖 亡魂 枪机",
"Gorgon Wraith Stock":"蛇发女妖 亡魂 枪托",
"Gorgon Wraith Blueprint":"蛇发女妖 亡魂 蓝图",
"Boltor Prime Blueprint":"螺钉步枪 PRIME 蓝图",
"Boltor Prime Barrel":"螺钉步枪 PRIME 枪管",
"Boltor Prime Receiver":"螺钉步枪 PRIME 枪机",
"Boltor Prime Stock":"螺钉步枪 PRIME 枪托",
"Cernos Prime Blueprint":"西诺斯 PRIME 蓝图",
"Cernos Prime Upper Limb":"西诺斯 PRIME 上弓臂",
"Cernos Prime Lower Limb":"西诺斯 PRIME 下弓臂",
"Cernos Prime Grip":"西诺斯 PRIME 弓身",
"Cernos Prime String":"西诺斯 PRIME 弓弦",
"Boar Prime Blueprint":"野猪 PRIME 蓝图",
"Boar Prime Barrel":"野猪 PRIME 枪管",
"Boar Prime Receiver":"野猪 PRIME 枪机",
"Boar Prime Stock":"野猪 PRIME 枪托",
"Dual Decurion Barrel":"什长双枪 枪管",
"Dual Decurion Receiver":"什长双枪 枪机",
"Imperator Vandal Blueprint":"凯旋将军 破坏者 蓝图",
"Imperator Vandal Barrel":"凯旋将军 破坏者 枪管",
"Imperator Vandal Receiver":"凯旋将军 破坏者 枪机",
"Cyngas Barrel":"合成燃气炮 枪管",
"Cyngas Receiver":"合成燃气炮 枪机",
"Cyngas Stock":"合成燃气炮 枪托",
"Fluctus Stock":"巨浪 枪托",
"Fluctus Barrel":"巨浪 枪管",
"Fluctus Limbs":"巨浪 弓臂",
"Velocitus Barrel":"极速电磁步枪 枪管",
"Velocitus Receiver":"极速电磁步枪 枪机",
"Velocitus Stock":"极速电磁步枪 枪托",
"Phaedra Barrel":"菲德菈 枪管",
"Phaedra Receiver":"菲德菈 枪机",
"Phaedra Stock":"菲德菈 枪托",
"Corvas Barrel":"黑鸦 枪管",
"Corvas Receiver":"黑鸦 枪机",
"Corvas Stock":"黑鸦 枪托",
"Wraith Twin Vipers Receiver":"双子蝰蛇 亡魂 枪机",
"Wraith Twin Vipers Barrel":"双子蝰蛇 亡魂 枪管",
"Wraith Twin Vipers Link":"双子蝰蛇 亡魂 连接器",
"Wraith Twin Vipers Blueprint":"双子蝰蛇 亡魂 蓝图",
"Akstiletto Prime Blueprint":"史提托双枪 PRIME 蓝图",
"Akstiletto Prime Barrel":"史提托双枪 PRIME 枪管",
"Akstiletto Prime Receiver":"史提托双枪 PRIME 枪机",
"Akstiletto Prime Link":"史提托双枪 PRIME 连接器",
"Ballistica Prime Blueprint":"布里斯提卡 PRIME 蓝图",
"Ballistica Prime Upper Limb":"布里斯提卡 PRIME 上弓臂",
"Ballistica Prime Lower Limb":"布里斯提卡 PRIME 下弓臂",
"Ballistica Prime Receiver":"布里斯提卡 PRIME 枪机",
"Ballistica Prime String":"布里斯提卡 PRIME 弓弦",
"Euphona Prime Blueprint":"悦音 PRIME 蓝图",
"Euphona Prime Barrel":"悦音 PRIME 枪管",
"Euphona Prime Receiver":"悦音 PRIME 枪机",
"Spira Prime Blueprint":"旋刃飞刀 PRIME 蓝图",
"Spira Prime Blade":"旋刃飞刀 PRIME 刀刃",
"Spira Prime Pouch":"旋刃飞刀 PRIME 镖袋",
"Sicarus Prime Blueprint":"暗杀者 PRIME 蓝图",
"Sicarus Prime Barrel":"暗杀者 PRIME 枪管",
"Sicarus Prime Receiver":"暗杀者 PRIME 枪机",
"Vasto Prime Blueprint":"瓦斯托 PRIME 蓝图",
"Vasto Prime Barrel":"瓦斯托 PRIME 枪管",
"Vasto Prime Receiver":"瓦斯托 PRIME 枪机",
"Akbolto Prime Blueprint":"螺钉双枪 PRIME 蓝图",
"Akbolto Prime Barrel":"螺钉双枪 PRIME 枪管",
"Akbolto Prime Receiver":"螺钉双枪 PRIME 枪机",
"Akbolto Prime Link":"螺钉双枪 PRIME 连接器",
"Bronco Prime Blueprint":"野马 PRIME 蓝图",
"Bronco Prime Barrel":"野马 PRIME 枪管",
"Bronco Prime Receiver":"野马 PRIME 枪机",
"Akbronco Prime Link":"野马双枪 PRIME 连接器",
"Lex Prime Blueprint":"雷克斯 PRIME 蓝图",
"Lex Prime Barrel":"雷克斯 PRIME 枪管",
"Lex Prime Receiver":"雷克斯 PRIME 枪机",
"Aklex Prime Link":"雷克斯双枪 PRIME 连接器",
"Hikou Prime Blueprint":"飞扬 PRIME 蓝图",
"Hikou Prime Stars":"飞扬 PRIME 星镖",
"Hikou Prime Pouch":"飞扬 PRIME 镖袋",
"ASH PRIME NEUROPTICS":"ASH PRIME 头部神经光元",
"ASH PRIME SYSTEMS":"ASH PRIME 系统",
"ASH PRIME CHASSIS":"ASH PRIME 机体",
"ASH PRIME BLUEPRINT":"ASH PRIME 蓝图",
"BANSHEE PRIME NEUROPTICS":"BANSHEE PRIME 头部神经光元",
"BANSHEE PRIME SYSTEMS":"BANSHEE PRIME 系统",
"BANSHEE PRIME CHASSIS":"BANSHEE PRIME 机体",
"BANSHEE PRIME BLUEPRINT":"BANSHEE PRIME 蓝图",
"EMBER PRIME NEUROPTICS":"EMBER PRIME 头部神经光元",
"EMBER PRIME SYSTEMS":"EMBER PRIME 系统",
"EMBER PRIME CHASSIS":"EMBER PRIME 机体",
"EMBER PRIME BLUEPRINT":"EMBER PRIME 蓝图",
"FROST PRIME NEUROPTICS":"FROST PRIME 头部神经光元",
"FROST PRIME SYSTEMS":"FROST PRIME 系统",
"FROST PRIME CHASSIS":"FROST PRIME 机体",
"FROST PRIME BLUEPRINT":"FROST PRIME 蓝图",
"HYDROID PRIME NEUROPTICS":"HYDROID PRIME 头部神经光元",
"HYDROID PRIME SYSTEMS":"HYDROID PRIME 系统",
"HYDROID PRIME CHASSIS":"HYDROID PRIME 机体",
"HYDROID PRIME BLUEPRINT":"HYDROID PRIME 蓝图",
"LOKI PRIME NEUROPTICS":"LOKI PRIME 头部神经光元",
"LOKI PRIME SYSTEMS":"LOKI PRIME 系统",
"LOKI PRIME CHASSIS":"LOKI PRIME 机体",
"LOKI PRIME BLUEPRINT":"LOKI PRIME 蓝图",
"MAG PRIME NEUROPTICS":"MAG PRIME 头部神经光元",
"MAG PRIME SYSTEMS":"MAG PRIME 系统",
"MAG PRIME CHASSIS":"MAG PRIME 机体",
"MAG PRIME BLUEPRINT":"MAG PRIME 蓝图",
"MIRAGE PRIME NEUROPTICS":"MIRAGE PRIME 头部神经光元",
"MIRAGE PRIME SYSTEMS":"MIRAGE PRIME 系统",
"MIRAGE PRIME CHASSIS":"MIRAGE PRIME 机体",
"MIRAGE PRIME BLUEPRINT":"MIRAGE PRIME 蓝图",
"NEKROS PRIME NEUROPTICS":"NEKROS PRIME 头部神经光元",
"NEKROS PRIME SYSTEMS":"NEKROS PRIME 系统",
"NEKROS PRIME CHASSIS":"NEKROS PRIME 机体",
"NEKROS PRIME BLUEPRINT":"NEKROS PRIME 蓝图",
"NOVA PRIME NEUROPTICS":"NOVA PRIME 头部神经光元",
"NOVA PRIME SYSTEMS":"NOVA PRIME 系统",
"NOVA PRIME CHASSIS":"NOVA PRIME 机体",
"NOVA PRIME BLUEPRINT":"NOVA PRIME 蓝图",
"OBERON PRIME NEUROPTICS":"OBERON PRIME 头部神经光元",
"OBERON PRIME SYSTEMS":"OBERON PRIME 系统",
"OBERON PRIME CHASSIS":"OBERON PRIME 机体",
"OBERON PRIME BLUEPRINT":"OBERON PRIME 蓝图",
"NYX PRIME NEUROPTICS":"NYX PRIME 头部神经光元",
"NYX PRIME SYSTEMS":"NYX PRIME 系统",
"NYX PRIME CHASSIS":"NYX PRIME 机体",
"NYX PRIME BLUEPRINT":"NYX PRIME 蓝图",
"RHINO PRIME NEUROPTICS":"RHINO PRIME 头部神经光元",
"RHINO PRIME SYSTEMS":"RHINO PRIME 系统",
"RHINO PRIME CHASSIS":"RHINO PRIME 机体",
"RHINO PRIME BLUEPRINT":"RHINO PRIME 蓝图",
"SARYN PRIME NEUROPTICS":"SARYN PRIME 头部神经光元",
"SARYN PRIME SYSTEMS":"SARYN PRIME 系统",
"SARYN PRIME CHASSIS":"SARYN PRIME 机体",
"SARYN PRIME BLUEPRINT":"SARYN PRIME 蓝图",
"TRINITY PRIME NEUROPTICS":"TRINITY PRIME 头部神经光元",
"TRINITY PRIME SYSTEMS":"TRINITY PRIME 系统",
"TRINITY PRIME CHASSIS":"TRINITY PRIME 机体",
"TRINITY PRIME BLUEPRINT":"TRINITY PRIME 蓝图",
"VALKYR PRIME NEUROPTICS":"VALKYR PRIME 头部神经光元",
"VALKYR PRIME SYSTEMS":"VALKYR PRIME 系统",
"VALKYR PRIME CHASSIS":"VALKYR PRIME 机体",
"VALKYR PRIME BLUEPRINT":"VALKYR PRIME 蓝图",
"VAUBAN PRIME NEUROPTICS":"VAUBAN PRIME 头部神经光元",
"VAUBAN PRIME SYSTEMS":"VAUBAN PRIME 系统",
"VAUBAN PRIME CHASSIS":"VAUBAN PRIME 机体",
"VAUBAN PRIME BLUEPRINT":"VAUBAN PRIME 蓝图",
"VOLT PRIME NEUROPTICS":"VOLT PRIME 头部神经光元",
"VOLT PRIME SYSTEMS":"VOLT PRIME 系统",
"VOLT PRIME CHASSIS":"VOLT PRIME 机体",
"VOLT PRIME BLUEPRINT":"VOLT PRIME 蓝图",
"AMESHA":"AMESHA",
"ELYTRON":"ELYTRON",
"ITZAL":"ITZAL",
"ODONATA":"ODONATA",
"ODONATA PRIME":"ODONATA PRIME",
"Taxon":"塔克桑",
"Djinn":"引灵",
"Carrier Sentinel":"搬运者",
"Dethcube":"死亡魔方",
"Diriga":"电气浮囊",
"Wyrm":"蛟龙",
"Helios Sentinel":"赫利俄斯",
"Shade Sentinel":"阴影",
"Carrier Prime":"搬运者 PRIME",
"Wyrm Prime":"蛟龙 PRIME",
"Helios Prime":"赫利俄斯 PRIME",
"Huras Kubrow":"匿踪型库狛",
"Chesa Kubrow":"寻猎型库狛",
"HELMINTH Charger":"HELMINTH 疾冲者",
"Sunika Kubrow":"猎杀型库狛",
"Sahasa Kubrow":"突击型库狛",
"Raksa Kubrow":"防护型库狛",
"Adarza Kavat":"镜像型库娃",
"Smeeta Kavat":"笑面型库娃",
"Prisma Shade":"棱晶 阴影",
"Arcane Grace":"优雅 赋能",
"Arcane Acceleration":"加速 赋能",
"Arcane Aegis":"神盾 赋能",
"Arcane Agility":"灵敏 赋能",
"Arcane Arachne":"蜘蛛 赋能",
"Arcane Avenger":"复仇者 赋能",
"Arcane Awakening":"觉醒 赋能",
"Arcane Barrier":"壁垒 赋能",
"Arcane Consequence":"结果 赋能",
"Arcane Deflection":"偏折 赋能",
"Arcane Energize":"充沛 赋能",
"Arcane Eruption":"爆发 赋能",
"Arcane Fury":"狂怒 赋能",
"Arcane Guardian":"保卫者 赋能",
"Arcane Healing":"复原 赋能",
"Arcane Ice":"冰冷 赋能",
"Arcane Momentum":"动量 赋能",
"Arcane Nullifier":"消磁 赋能",
"Arcane Phantasm":"幻象 赋能",
"Arcane Precision":"精确 赋能",
"Arcane Pulse":"生机 赋能",
"Arcane Rage":"愤怒 赋能",
"Arcane Resistance":"电阻 赋能",
"Arcane Strike":"速攻 赋能",
"Arcane Trickery":"诡计 赋能",
"Arcane Ultimatum":"通牒 赋能",
"Arcane Velocity":"迅速 赋能",
"Arcane Victory":"胜利 赋能",
"Arcane Warmth":"温暖 赋能",
"Magus Vigor":"魔导 活力",
"Virtuos Null":"正直 空无",
"Magus Husk":"魔导 外壳",
"Virtuos Tempo":"正直 节奏",
"Virtuos Fury":"正直 狂怒",
"Magus Cloud":"魔导 游云",
"Virtuos Strike":"正直 打击",
"Magus Cadence":"魔导 韵律",
"Virtuos Ghost":"正直 鬼魅",
"Magus Replenish":"魔导 充盈",
"Virtuos Shadow":"正直 暗影",
"Magus Elevate":"魔导 振奋",
"Magus Nourish":"魔导 滋养",
"Exodia Brave":"神威 勇武",
"Exodia Valor":"神威 勇猛",
"Exodia Might":"神威 力量",
"Exodia Triumph":"神威 凯旋",
"Exodia Hunt":"神威 狩猎",
"Exodia Force":"神威 气力",
"Exodia Epidemic":"神威 流行病",
"Exodia Contagion":"神威 触染",
"Ayr Ayatan Sculpture":"阿耶檀识 AYR 塑像",
"Piv Ayatan Sculpture":"阿耶檀识 PIV 塑像",
"Sah Ayatan Sculpture":"阿耶檀识 SAH 塑像",
"Orta Ayatan Sculpture":"阿耶檀识 ORTA 塑像",
"Vaya Ayatan Sculpture":"阿耶檀识 VAYA 塑像",
"Anasa Ayatan Sculpture":"阿耶檀识 ANASA 塑像",
"Valana Ayatan Sculpture":"阿耶檀识 VALANA 塑像",
"Kavasa Prime Collar":"喀婆萨 PRIME 库狛项圈",
"SCIMITAR":"SCIMITAR",
"LISET":"LISET",
"XIPHOS":"XIPHOS",
"MANTIS":"MANTIS",
"Kavasa Prime Collar Blueprint":"喀婆萨 PRIME 项圈 蓝图",
"Kavasa Prime Collar Band":"喀婆萨 PRIME 项圈 项圈带",
"Kavasa Prime Collar Buckle":"喀婆萨 PRIME 项圈 项圈扣",
"Carrier Prime Blueprint":"搬运者 PRIME 蓝图",
"Wyrm Prime Blueprint":"蛟龙 PRIME 蓝图",
"Helios Prime Blueprint":"赫利俄斯 PRIME 蓝图",
"Carrier Prime Cerebrum":"搬运者 PRIME 头部神经光元",
"Wyrm Prime Cerebrum":"蛟龙 PRIME 头部神经光元",
"Helios Prime Cerebrum":"赫利俄斯 PRIME 头部神经光元",
"Carrier Prime Carapace":"搬运者 PRIME 外壳",
"Wyrm Prime Carapace":"蛟龙 PRIME 外壳",
"Helios Prime Carapace":"赫利俄斯 PRIME 外壳",
"Carrier Prime Systems":"搬运者 PRIME 系统",
"Wyrm Prime Systems":"蛟龙 PRIME 系统",
"Helios Prime Systems":"赫利俄斯 PRIME 系统",
"Akbronco Prime Blueprint":"野马双枪 PRIME 蓝图",
"Aklex Prime Blueprint":"雷克斯双枪 PRIME 蓝图",
"Odonata Prime Blueprint":"ODONATA PRIME 蓝图",
"Odonata Prime Wings":"ODONATA PRIME 机翼",
"Odonata Prime Harness":"ODONATA PRIME 外甲",
"Odonata Prime Systems":"ODONATA PRIME 系统",
"Scimitar Fuselage":"SCIMITAR 机身",
"Scimitar Engines":"SCIMITAR 引擎",
"Scimitar Avionics":"SCIMITAR 飞航系统",
"Xiphos Fuselage":"XIPHOS 机身",
"Xiphos Engines":"XIPHOS 引擎",
"Xiphos Avionics":"XIPHOS 飞航系统",
"Mantis Fuselage":"MANTIS 机身",
"Mantis Engines":"MANTIS 引擎",
"Mantis Avionics":"MANTIS 飞航系统",
"cr":"星币",
"Endo":"内融核心",
"Kubrow Egg":"库狛蛋",
"Kavat Genetic Code":"库娃遗传密码",
"Orokin Catalyst":"OROKIN催化剂",
"Orokin Reactor":"OROKIN反应堆",
"FORMA":"FORMA",
"ASH PRIME":"阿什 PRIME",
"BANSHEE PRIME":"音妈 PRIME",
"EMBER PRIME":"火鸡 PRIME",
"FROST PRIME":"冰男 PRIME",
"HYDROID PRIME":"水男 PRIME",
"LOKI PRIME":"洛基 PRIME",
"MAG PRIME":"磁妹 PRIME",
"MIRAGE PRIME":"小丑 PRIME",
"NEKROS PRIME":"摸尸 PRIME",
"NOVA PRIME":"诺娃 PRIME",
"OBERON PRIME":"奶爸 PRIME",
"NYX PRIME":"脑溢血 PRIME",
"RHINO PRIME":"犀牛 PRIME",
"SARYN PRIME":"毒妈 PRIME",
"TRINITY PRIME":"奶妈 PRIME",
"VALKYR PRIME":"女汉子 PRIME",
"VAUBAN PRIME":"工程 PRIME",
"VOLT PRIME":"电男 PRIME",
"ASH":"阿什",
"BANSHEE":"音妈",
"EMBER":"火鸡",
"FROST":"冰男",
"HYDROID":"水男",
"LOKI":"洛基",
"MAG":"磁妹",
"MIRAGE":"小丑",
"NEKROS":"摸尸",
"NOVA":"诺娃",
"OBERON":"奶爸",
"NYX":"脑溢血",
"RHINO":"犀牛",
"SARYN":"毒妈",
"TRINITY":"奶妈",
"VALKYR":"女汉子",
"VAUBAN":"工程",
"VOLT":"电男",
"ATLAS":"土甲",
"CHROMA":"龙甲",
"EQUINOX":"扶她",
"EXCALIBUR":"EXCALIBUR",
"GARA":"玻璃甲",
"HARROW":"主教",
"INAROS":"沙甲",
"IVARA":"弓妹",
"LIMBO":"李明博",
"MESA":"女枪",
"NEZHA":"哪吒",
"NIDUS":"蛆甲",
"OCTAVIA":"音乐甲",
"TITANIA":"TITANIA",
"WUKONG":"悟空",
"ZEPHYR":"鸟姐",
"Madurai Lens":"MADURAI晶体",
"Naramon Lens":"NARAMON晶体",
"Vazarin Lens":"VAZARIN晶体",
"Unairu Lens":"UNAIRU晶体",
"Zenurik Lens":"ZENURIK晶体",
"Eidolon Lens":"夜灵晶体",
"Greater Madurai Lens":"MADURAI高级晶体",
"Greater Vazarin Lens":"VAZARIN高级晶体",
"Greater Naramon Lens":"NARAMON高级晶体",
"Greater Unairu Lens":"UNAIRU高级晶体",
"Greater Zenurik Lens":"ZENURIK高级晶体",
"Cressa's Garrison Scene":"CRESSA的驻扎处场景",
"Arbiter's Tribunal Scene":"仲裁者法庭场景",
"Suda's Datascape Scene":"苏达数据景观场景",
"Hunhow's Datascape Scene":"HUNHOW的数据景观场景",
"Ergo's Boardroom Scene":"ERGO的会议室场景",
"Veil's Binding Scene":"VEIL的拘束台场景",
"Harrow's Temple Scene":"HARROW神庙场景",
"Amaryn's Retreat Scene":"AMARYN的避难所场景",
"Grineer Forest Factory Scene":"GRINEER森林工厂场景",
"Grineer Forest Industry Scene":"GRINEER森林工业场景",
"Grineer Forest Water Pump Scene":"GRINEER森林水泵场景",
"Inaros Tomb Scene":"INAROS古墓场景",
"Plains of Eidolon Scene":"夜灵平野场景",
"Color Key Scene":"色键场景",
"Prisma Daedalus":"棱晶 代达罗斯",
"Prisma Sigil":"棱晶纹章",
"Prisma Mech Head Sentinel Mask":"棱晶 机甲头盔面具",
"Prisma Hecate Syandana":"棱晶 朔月女神披饰",
"Prisma Jet Sentinel Wings":"棱晶 喷射机翼",
"Prisma Yamako Syandana":"棱晶 山越披饰",
"Prisma Arrows":"棱晶箭矢",
"Prisma Koi Sentinel Tail":"棱晶 喷射尾翼",
"Prisma Edo":"棱晶 江户",
"Prisma Naberus":"棱晶 恶魔纳贝流士",
"Baro Ki'Teer Noggle":"BARO KI'TEER 摇头娃娃",
"3-Day Affinity Booster":"3天经验加成",
"3-Day Credit Booster":"3天现金加成",
"3 Day Resource Booster":"3天资源数量加成",
"Grustrag Three Beacon":"三霸信标",
"Stalker Beacon":"STALKER信标",
"Zanuka Hunter Beacon":"ZANUKA信标",
"Sands of Inaros Blueprint":"INAROS之沙",
"Falcon Mod Pack":"猎鹰MOD包",
"Dragon Mod Pack":"恶龙MOD包",
"Ki'teer Glyph":"KI'TEER头像",
"Baro Ki'teer Colors":"BARO KI'TEER 色板",
"Pedestal Prime":"基座 PRIME",
"Ki'Teer Fireworks":"KI'TEER 烟花",
"Corrupted Bombard Specter":"堕落轰击者魅影",
"Nexus Gene-Masking Kit":"纳瑟斯基因伪装包",
"Ki'Teer Presence":"KI'TEER 姿态",
"Display - Argyle":"展示图-菱形",
"Ki'Teer Tribute Glyph":"KI'TEER 致敬浮印",
"Kavat Pet Mask":"库娃守护面具",
"Kavat Pet Wings":"库娃守护飞翼",
"Kavat Sentinel Tail":"库娃守护尾翼",
"Ki'Teer Sentinel Mask":"KI'TEER 守护面具",
"Ki'Teer Sentinel Wings":"KI'TEER 守护飞翼",
"Ki'Teer Sentinel Tail":"KI'TEER 守护尾翼",
"Ki'Teer Syandana":"KI'TEER 披饰",
"Ki'Teer Arrow":"KI'TEER 箭矢外观",
"Ki'Teer Kubrow Armor":"KI'TEER 库狛装甲",
"Ki'Teer Diax Syandana":"KI'TEER 大亚披饰",
"Ki'Teer Sekhara":"KI'TEER 饰冠",
"Ki'Teer Earpiece":"KI'TEER 耳饰",
"Ki'Teer Solo Earpiece":"KI'TEER 单个耳饰",
"Nexus Fur Pattern":"纳瑟斯毛皮花纹",
"Ki'Teer Kavat Armor":"KI'TEER 库娃护甲",
"Solstice Ki'teer Syandana":"KI'TEER 冬至披饰",
"Ki'Teer Sugatra":"KI'TEER 坠饰",
"Ki'Teer Razza Syandana":"KI'TEER 类种披饰",
"Ki'Teer Foros":"KI'TEER 福罗斯",
"Eos Prime Armor":"曙光女神 PRIME",
"Pyra Sugatra":"佩拉坠饰",
"Larva Burst":"幼体爆发",
"Lasting Covenant":"持久誓约",
"Razorwing Blitz":"刀翼闪击",
"Nidus Prion Helmet":"NIDUS 朊毒头盔",
"Frost Squall Helmet":"FROST 飑风头盔",
"Banshee Reverb Helmet":"BANSHEE 返响头盔",
"Valkyr Kara Helmet":"VALKYR 狂者头盔",
"Ember Backdraft Helmet":"EMBER 复燃头盔",
"Loki Essence Helmet":"LOKI 本质头盔",
"Mag Coil Helmet":"MAG 线圈头盔",
"Trinity Meridian Helmet":"TRINITY 经络头盔",
"Octavia Cadenza Helmet":"OCTAVIA 华彩乐章头盔",
"Frost Aurora Helmet":"FROST 极光头盔",
"Atlas Shikoro Helmet":"ATLAS 兜围头盔",
"Volt Storm Helmet":"VOLT 风暴头盔",
"Saryn Hemlock Helmet":"SARYN 铁杉头盔",
"Nyx Menticide Helmet":"NYX 灭神头盔",
"Banshee Chorus Helmet":"BANSHEE 合音头盔",
"Hydroid Ketos Helmet":"HYDROID 海怪头盔",
"Chroma Drac Helmet":"CHROMA 龙蛇头盔",
"Ember Phoenix Helmet":"EMBER 凤凰头盔",
"Valkyr Bastet Helmet":"VALKYR 芭丝特头盔",
"Nova Flux Helmet":"NOVA 通量头盔",
"Ash Scorpion Helmet":"ASH 毒蝎头盔",
"Mag Gauss Helmet":"MAG 高斯头盔",
"Volt Pulse Helmet":"VOLT 脉冲头盔",
"Chroma Amaru Helmet":"CHROMA 羽蛇神头盔",
"Hydroid Rorqual Helmet":"HYDROID 鳁鲸头盔",
"Limbo Magrite Helmet":"LIMBO 画家头盔",
"Limbo Aristeas Helmet":"LIMBO 诗人头盔",
"Nyx Vespa Helmet":"NYX 黄蜂头盔",
"Atlas Tartarus Helmet":"ATLAS 炼狱头盔",
"Hydroid Triton Helmet":"HYDROID 海之信使头盔",
"Ash Locust Helmet":"ASH 飞蝗头盔",
"Rhino Thrak Helmet":"RHINO 震击头盔",
"Rhino Vanguard Helmet":"RHINO 先锋头盔",
"Ivara Zirastra Helmet":"IVARA 头罩头盔",
"Ivara Loxley Helmet":"IVARA 洛克斯利头盔",
"Wukong Dasheng Helmet":"WUKONG 大圣头盔",
"Wukong Macak Helmet":"WUKONG 猕猴头盔",
"Equinox Solstice Helmet":"EQUINOX 至点头盔",
"Excalibur Pendragon Helmet":"EXCALIBUR 潘德拉冈头盔",
"Excalibur Mordred Helmet":"EXCALIBUR 莫德雷头盔",
"Excalibur Avalon Helmet":"EXCALIBUR 阿瓦隆头盔",
"Gara Virago Helmet":"GARA 悍妇头盔",
"Inaros Anubis Helmet":"INAROS 阿努比斯头盔",
"Inaros Canopic Helmet":"INAROS 卡诺比斯头盔",
"Loki Enigma Helmet":"LOKI 谜样头盔",
"Loki Swindle Helmet":"LOKI 诈欺头盔",
"Mesa Longhorn Helmet":"MESA 长角头盔",
"Mesa Ovis Helmet":"MESA 角羊头盔",
"Mirage Harlequin Helmet":"MIRAGE 丑角头盔",
"Mirage Trivelin Helmet":"MIRAGE 丑仆头盔",
"Nekros Raknis Helmet":"NEKROS 古墓头盔",
"Nekros Shroud Helmet":"NEKROS 裹尸布头盔",
"Nezha Circa Helmet":"NEZHA 奇尔卡头盔",
"Nova Quantum Helmet":"NOVA 量子头盔",
"Nova Slipstream Helmet":"NOVA 气流头盔",
"Oberon Markhor Helmet":"OBERON 捻角山羊头盔",
"Oberon Oryx Helmet":"OBERON 羚羊头盔",
"Saryn Chlora Helmet":"SARYN 氯毒头盔",
"Titania Aurai Helmet":"TITANIA 风之妖精头盔",
"Trinity Aura Helmet":"TRINITY 预言头盔",
"Vauban Armistice Helmet":"VAUBAN 休战头盔",
"Vauban Chapelon Helmet":"VAUBAN 沙佩隆头盔",
"Vauban Esprit Helmet":"VAUBAN 机敏头盔",
"Vauban Gambit Helmet":"VAUBAN 策略头盔",
"Zephyr Cierzo Helmet":"ZEPHYR 西熟风头盔",
"Zephyr Tengu Helmet":"ZEPHYR 天狗头盔",
"Harrow Suffragan Helmet":"HARROW 副主教头盔",
"Fragor Brokk Skin":"重击巨锤 布洛克外观",
"Dagger Axe Zoren Skin":"佐轮双斧 戈刃外观",
"Scindo Manticore Skin":"分裂战斧 蝎尾狮外观",
"Dagger Axe Scindo Skin":"分裂斩斧 戈刃外观",
"Axi A1":"后纪 A1",
"Axi A2":"后纪 A2",
"Axi A3":"后纪 A3",
"Axi B1":"后纪 B1",
"Axi B2":"后纪 B2",
"Axi C1":"后纪 C1",
"Axi C2":"后纪 C2",
"Axi E1":"后纪 E1",
"Axi E2":"后纪 E2",
"Axi G1":"后纪 G1",
"Axi H1":"后纪 H1",
"Axi H2":"后纪 H2",
"Axi K1":"后纪 K1",
"Axi N1":"后纪 N1",
"Axi N2":"后纪 N2",
"Axi N3":"后纪 N3",
"Axi N4":"后纪 N4",
"Axi N5":"后纪 N5",
"Axi O1":"后纪 O1",
"Axi R1":"后纪 R1",
"Axi S1":"后纪 S1",
"Axi T1":"后纪 T1",
"Axi V1":"后纪 V1",
"Axi V2":"后纪 V2",
"Axi V3":"后纪 V3",
"Axi V4":"后纪 V4",
"Axi V5":"后纪 V5",
"Axi V6":"后纪 V6",
"Axi V7":"后纪 V7",
"Lith A1":"古纪 A1",
"Lith A2":"古纪 A2",
"Lith B1":"古纪 B1",
"Lith B2":"古纪 B2",
"Lith C1":"古纪 C1",
"Lith C2":"古纪 C2",
"Lith F1":"古纪 F1",
"Lith F2":"古纪 F2",
"Lith G1":"古纪 G1",
"Lith H1":"古纪 H1",
"Lith K1":"古纪 K1",
"Lith M1":"古纪 M1",
"Lith N1":"古纪 N1",
"Lith N2":"古纪 N2",
"Lith N3":"古纪 N3",
"Lith S1":"古纪 S1",
"Lith S2":"古纪 S2",
"Lith S3":"古纪 S3",
"Lith S4":"古纪 S4",
"Lith S5":"古纪 S5",
"Lith S6":"古纪 S6",
"Lith S7":"古纪 S7",
"Lith T1":"古纪 T1",
"Lith V1":"古纪 V1",
"Lith V2":"古纪 V2",
"Lith V3":"古纪 V3",
"Lith V4":"古纪 V4",
"Meso B1":"前纪 B1",
"Meso C1":"前纪 C1",
"Meso C2":"前纪 C2",
"Meso C3":"前纪 C3",
"Meso D1":"前纪 D1",
"Meso F1":"前纪 F1",
"Meso F2":"前纪 F2",
"Meso G1":"前纪 G1",
"Meso H1":"前纪 H1",
"Meso K1":"前纪 K1",
"Meso M1":"前纪 M1",
"Meso N1":"前纪 N1",
"Meso N2":"前纪 N2",
"Meso N3":"前纪 N3",
"Meso N4":"前纪 N4",
"Meso N5":"前纪 N5",
"Meso O1":"前纪 O1",
"Meso S1":"前纪 S1",
"Meso S2":"前纪 S2",
"Meso S3":"前纪 S3",
"Meso S4":"前纪 S4",
"Meso S5":"前纪 S5",
"Meso S6":"前纪 S6",
"Meso V1":"前纪 V1",
"Meso V2":"前纪 V2",
"Meso V3":"前纪 V3",
"Meso V4":"前纪 V4",
"Meso V5":"前纪 V5",
"Neo A1":"中纪 A1",
"Neo B1":"中纪 B1",
"Neo B2":"中纪 B2",
"Neo B3":"中纪 B3",
"Neo D1":"中纪 D1",
"Neo H1":"中纪 H1",
"Neo M1":"中纪 M1",
"Neo N1":"中纪 N1",
"Neo N2":"中纪 N2",
"Neo N3":"中纪 N3",
"Neo N4":"中纪 N4",
"Neo N5":"中纪 N5",
"Neo N6":"中纪 N6",
"Neo N7":"中纪 N7",
"Neo S1":"中纪 S1",
"Neo S2":"中纪 S2",
"Neo S3":"中纪 S3",
"Neo S5":"中纪 S5",
"Neo S6":"中纪 S6",
"Neo S7":"中纪 S7",
"Neo S8":"中纪 S8",
"Neo T1":"中纪 T1",
"Neo V1":"中纪 V1",
"Neo V2":"中纪 V2",
"Neo V3":"中纪 V3",
"Neo V4":"中纪 V4",
"Neo V5":"中纪 V5",
"Neo V6":"中纪 V6",
"Exilus Adapter":"特殊功能槽连接器",
"Lith G2":"古纪 G2",
"Meso E1":"前纪 E1",
"Meso F3":"前纪 F3",
"Neo E1":"中纪 E1",
"Neo F1":"中纪 F1",
"Axi L1":"后纪 L1",
"Axi S2":"后纪 S2",
"Shotgun Riven Mod (Veiled)":"霰弹枪 未开紫卡",
"Melee Riven Mod (Veiled)":"近战 未开紫卡",
"Rifle Riven Mod (Veiled)":"步枪 未开紫卡",
"Pistol Riven Mod (Veiled)":"手枪 未开紫卡",
"Encrypted Journal Fragment":"加密的日记碎片",
"Mercury":"水星",
"Lua":"月球",
"Venus":"金星",
"Earth":"地球",
"Mars":"火星",
"Jupiter":"木星",
"Saturn":"土星",
"Uranus":"天王星",
"Neptune":"海王星",
"Pluto":"冥王星",
"Phobos":"火卫一",
"Ceres":"谷神星",
"Europa":"欧罗巴",
"Sedna":"赛德娜",
"Kuva Fortress":"赤毒要塞",
"Eris":"阋神星",
"Void":"虚空",
"Assassination":"刺杀",
"Assault":"强袭",
"Capture":"捕获",
"Defense":"防御",
"Defection":"叛逃",
"Excavation":"挖掘",
"Hive":"清巢",
"Spy":"间谍",
"Free Roam":"自由漫步",
"Mobile Defense":"移动防御",
"Conclave":"武形秘仪",
"Rescue":"救援",
"Hijack":"劫持",
"Sabotage":"破坏",
"Dark Sector":"黑暗地带",
"Survival":"生存",
"Interception":"拦截",
"Lith":"古纪",
"Meso":"前纪",
"Neo":"中纪",
"Axi":"后纪",
"Sonicor Exilis Skin":"超音波冲击枪 镀铜外观",
"Left Prisma Daedalus Knee Plates":"棱晶 代达罗斯 左护膝板",
"Right Prisma Daedalus Knee Plates":"棱晶 代达罗斯 右护膝板",
"Left Prisma Daedalus Shoulderguard":"棱晶 代达罗斯 左护肩",
"Right Prisma Daedalus Shoulderguard":"棱晶 代达罗斯 右护肩",
"Zephyr Immortal Skin":"ZEPHYR 不朽外观",
"Noggle Statue - Baro Ki'teer":"BARO KI'TEER 摇头娃娃",
"双子葛拉卡达 夏至外观":"Twin Grakata Towsun Skin",
"Ki'teer Leg Plates":"KI'TEER 腿部护甲",
"Ki'teer Shoulder Plates":"KI'TEER 肩部护甲",
"Ki'teer Chest Plate":"KI'TEER 胸部护甲",
"Primed Pistol Ammo Mutation":"手枪弹药转换 PRIME",
"Twin Grakata Towsun Skin":"双子葛拉卡达 夏至外观",
"Extermination":"歼灭",
"Orokin Sabotage":"虚空破坏",
"EXCALIBUR PRIME":"咖喱 PRIME",
"Day Of The Dead Kavat Armor":"库娃护甲 亡灵节外观",
"Ki'teer Atmos Mask":"Ki'Teer 大气面罩",
"Ki'teer Atmos Earpiece":"Ki'Teer 大气耳饰",
"Baro Kiteer Sekhara":"Ki'Teer 饰冠",
"Prisma Naberus Arm Armor":"棱晶 恶魔纳贝流士",
"Liset Scarf":"LISET 亡灵节外观",
"Redeemer Elixis Skin":"救赎者 镀铜外观",
"Scimitar Prisma Skin":"SCIMITAR 棱晶外观",
"Left Prisma Edo Shoulder Armor":"棱晶 江户 左肩甲",
"Right Prisma Edo Shoulder Armor":"棱晶 江户 右肩甲",
"Right Prisma Edo Knee Plates":"棱晶 江户 右膝甲",
"Left Prisma Edo Knee Plates":"棱晶 江户 左膝甲",
"Prisma Edo Chest Plate":"棱晶 江户 胸甲",
"Anpu Staff Skin":"安普长棍外观",
"Anpu Sugatra":"安普坠饰",
"Hydroid Immortal Skin":"Hydroid 不朽外观",
"Liset Prisma Skin":"LISET 棱晶外观",
"Vermillion Storm":"朱红暴风",
"Ki'teer Atmos Diadem":"KI'TEER 大气头饰",
"Ki'teer Razza Synadana":"KI'TEER 类种披饰",
"Axi V8":"后纪 V8",
"Neo O1":"中纪 O1",
"Primed Vigor":"活力 PRIME",
"Legendary Fusion Core":"传说核心",
"Lith H2":"古纪 H2",
"Lith Z1":"古纪 Z1",
"Meso O2":"前纪 O2",
"Meso T1":"前纪 T1",
"Meso T2":"前纪 T2",
"Neo B4":"中纪 B4",
"Neo K1":"中纪 K1",
"Neo Z1":"中纪 Z1",
"Axi H3":"后纪 H3",
"Axi K2":"后纪 K2",
"Axi Q2":"后纪 Q2",
"Zephyr Prime":"鸟姐 PRIME",
"Kronen Prime":"皇家拐刃 PRIME",
"Tiberon Prime":"狂鲨 PRIME",
"Photobooth Tile Orokin Extraction":"OROKIN堡垒撤离点场景",
"Quanta Aufeis Skin":"量子切割器 积冰外观",
"Mantis Prisma Skin":"MANTIS 棱晶外观",
"Baro Emote":"KI'TEER的仪态",
"Arcane Tempo":"节奏 赋能",
"Nezha Jinza Helmet":"NEZHA 金吒头盔",
"Cyan Ayatan Star":"阿耶檀识青蓝星",
"Amber Ayatan Star":"阿耶檀识琥珀星",
"Elixis Odonata Skin":"ODONATA 镀铜外观",
"Excalibur Archwing Bobble Head":"摇头娃娃-装备ODONATA的EXCALIBUR",
"Primed Rifle Ammo Mutation":"步枪弹药转换 PRIME",
"Primed Shotgun Ammo Mutation":"霰弹枪弹药转换 PRIME",
"Eos Prime Armor Set":"曙光女神 PRIME 装甲组合",
"Eos Prime Chest Plate":"曙光女神 PRIME 胸甲",
"Left Eos Prime Shoulder Plates":"曙光女神 PRIME 左肩甲",
"Right Eos Prime Shoulder Plates":"曙光女神 PRIME 右肩甲",
"Left Eos Prime Spurs":"曙光女神 PRIME 左马刺",
"Right Eos Prime Spurs":"曙光女神 PRIME 右马刺",
"Prisma Daedalus Chest Plate":"棱晶 代达罗斯 胸甲",
"Corrupted Bombard Specter Blueprint":"堕落轰击者魅影 蓝图",
"Domus Syandana":"家宅披饰",
"Energy Transfer":"能量转移",
"Reaping Chakram":"割魂火圈",
"Mesa’s Waltz":"Mesa的华尔兹",
"Concentrated Arrow":"集中箭矢",
"Balla":"宝拉",
"Cyath":"西亚什",
"Dehtat":"德塔特",
"Kronsh":"客隆什",
"Mewan":"密丸",
"Ooltha":"乌尔萨",
"Plague Keewar":"瘟疫 奇沃",
"Plague Kripath":"瘟疫 克里帕丝",
"Jayap":"查亚普",
"Kroostra":"克鲁斯查",
"Kwath":"库阿斯",
"Laka":"拉卡",
"Peye":"佩耶",
"Seekalla":"斯卡拉",
"Plague Akwin":"瘟疫 艾克文",
"Plague Bokwin":"瘟疫 柏克文",
"Ruhang":"如杭",
"Jai":"翟",
"Ruhang II":"如杭 II",
"Jai II":"翟 II",
"Vargeet Ruhang":"瓦吉特 如杭",
"Ekwana Ruhang":"伊克瓦纳 如杭",
"Vargeet Jai":"瓦吉特 翟",
"Ekwana Jai":"伊克瓦纳 翟",
"Ekwana II Ruhang":"伊克瓦纳 II 如杭",
"Vargeet II Ruhang":"瓦吉特 II 如杭",
"Vargeet II Jai":"瓦吉特 II 翟",
"Ekwana II Jai":"伊克瓦纳 II 翟",
"Vargeet Ruhang II":"瓦吉特 如杭 II",
"Ekwana Ruhang II":"伊克瓦纳 如杭 II",
"Vargeet Jai II":"瓦吉特 翟 II",
"Ekwana Jai II":"伊克瓦纳 翟 II",
"Plan B":"应急备案",
"Hystrix":"豪猪",
"Dual Keres":"双持凯瑞斯",
"Veldt":"草原猎手",
"Khora":"蜘蛛甲",
"Sephahn":"瑟普梵",
"Rabvee":"拉比威",
"Dokrahm":"多克拉姆",
"Peculiar Bloom":"花开怪奇",
"Khora Delphi Helmet":"KHORA 德尔菲头盔",
"Grineer Settlement Artillery Scene":"GRINEER驻扎地火炮场景",
"Lua Balcony Scene":"月球楼厅场景",
"Grineer Sealab Centrifuge Scene":"GRINEER海底实验室离心机场景",
"Corpus Ship Freight Scene":"CORPUS船货场景",
"Kuva Fortress Crevice Scene":"赤毒要塞裂缝场景",
"Orokin Derelict Plaza Scene":"OROKIN荒废广场场景",
"Grineer Settlement Reactor Scene":"GRINEER居住点反应炉场景",
"Lua Nursery Scene":"月球苗圃场景",
"Corpus Ice Planet Wreckage Scene":"CORPUS冰封星球残骸场景",
"Corpus Gas City Conduit Scene":"CORPUS集气城市管道场景",
"Infested Ship Bridge Scene":"INFESTED舰桥场景",
"Grineer Shipyards Manufactory Scene":"GRINEER造船厂场景",
"Ki'teer Foros Shoulder Plates":"KI'TEER 福罗斯 胸部护甲",
"Ki'teer Foros Leg Plates":"KI'TEER 福罗斯 腿部护甲",
"Ki'teer Foros Chest Plate":"KI'TEER 福罗斯 肩部护甲",
"Corrupted Heavy Gunner Ball":"堕落重型机枪兵魅影",
"Khora Alt Helmet Blueprint":"KHORA 德尔菲头盔",
"Mutalist Alad V Nav Coordinate":"异融ALAD V导航座标",
"Negate":"抵消",
"Reawaken":"再启动",
"Peculiar Growth":"生长怪奇",
"Equinox Clisthert Helmet":"EQUINOX 晨昏恶魔头盔",
"Xiphos Prisma Skin":"XIPHOS 棱晶外观",
"Elixis Opticor":"奥堤克光子枪 镀铜外观",
"Captain Vor":"VOR 上尉",
"Councilor Vay Hek":"Vay Hek议员",
"General Sargus Ruk":"RUK将军",
"Lech Kril":"LECH KRIL中尉",
"Jackal":"豺狼",
"Hyena Pack":"鬣狗群",
"Raptor":"猛禽",
"Mutalist Alad V":"异融者ALAD V",
"Assault Rifle":"突击步枪",
"Weapon Restriction":"武器限定",
"Pistol":"手枪",
"Melee":"近战",
"Bow":"弓箭",
"Shotgun":"霰弹枪",
"Sniper":"狙击枪",
"Enemy Elemental Enhancement":"敌人元素强化",
"Corrosive":"腐蚀",
"Electricity":"电击",
"Blast":"爆炸",
"Heat":"火焰",
"Cold":"冰冻",
"Gas":"毒气",
"Magnetic":"磁力",
"Toxin":"毒素",
"Radiation":"辐射",
"Viral":"病毒",
"Impact":"冲击",
"Puncture":"穿刺",
"Enemy Physical Enhancement":"敌人物理强化",
"Slash":"切割",
"Augmented Enemy Armor":"敌人护甲强化",
"Eximus Stronghold":"卓越者大本营",
"Energy Reduction":"能量上限减少",
"Enhanced Enemy Shields":"敌人护盾强化",
"Environmental Effect":"环境改变",
"Environmental Hazard":"环境灾害",
"Extreme Cold":"极寒",
"Fire":"火灾",
"Dense Fog":"浓雾",
"Cryogenic Leakage":"冷却液泄露",
"Electromagnetic Anomalies":"电磁异常",
"Radiation Pockets":"辐射灾害",
"Pack Leader Sigil":"领袖纹章",
"Glaring Sigil":"耀目纹章",
"Excalibur Umbra":"暗影咖喱",
"Ki'teer Atmos Oculus":"KI'TEER 大气眼饰",
"Limbo Prime":"李明博 PRIME",
"Destreza Prime":"技巧之剑 PRIME",
"Pyrana Prime":"食人鱼 PRIME",
"Skiajati":"影生",
"Empowered Quiver":"强化箭袋",
"Insatiable":"不竭贪婪",
"Warding Thurible":"庇护焚炉",
"Partitioned Mallet":"分裂槌音",
"Umbral Intensify":"暗影 聚精会神",
"Umbral Vitality":"暗影 生命力",
"Umbral Fiber":"暗影 纤维",
"Sacrificial Steel":"牺牲 斩铁",
"Sacrificial Pressure":"牺牲 压迫点",
"Gorgon Towsun Skin":"蛇发女妖 夏至外观",
"Prisma Razor Scarf":"棱晶 乌鲁披饰",
"Melee Damage":"近战伤害",
"Physical Damage":"物理伤害",
"Critical Chance":"暴击率",
"Critical Damage":"暴击伤害",
"Elemental Damage":"元素伤害",
"Status Chance":"触发几率",
"Status Duration":"状态持续时间",
"Damage to Faction":"对派系伤害",
"Attack Speed":"攻击速度",
"Channeling Efficiency":"充能效率",
"Channeling Damage":"充能伤害",
"Finisher Damage":"处决伤害",
"Range":"攻击范围",
"Chance to be a Critical Hit":"滑行攻击造成暴击几率",
"Combo Duration":"连击持续时间",
"Multishot":"多重射击",
"Fire Rate (x2 for Bows)":"射速（弓类武器效果加倍）",
"Magazine Capacity":"弹匣容量",
"Ammo Maximum":"弹药最大值",
"Flight Speed":"弹道飞行速度",
"Reload Speed":"装填速度",
"Weapon Recoil":"武器后坐力",
"Zoom":"变焦",
"Punch Through":"穿透",
"Fire Rate":"射速",
"Cold Damage":"冰冻伤害",
"Electricity Damage":"电击伤害",
"Heat Damage":"火焰伤害",
"Toxin Damage":"毒素伤害",
"Impact Damage":"冲击伤害",
"Puncture Damage":"穿刺伤害",
"Slash Damage":"切割伤害",
"Damage to Grineer":"对G系伤害",
"Damage to Infested":"对I系伤害",
"Damage to Corpus":"对C系伤害",
"Rifle":"步枪",
"Damage":"伤害",
"Exterminate":"歼灭",
"Little Money":"小钱钱",
"So So":"有点积蓄",
"Success Man":"成功人士",
"Earn Money":"赚钱能手",
"Lots Money":"身揣巨款",
"Iron Man":"土豪",
"Batman":"大财阀",
"Score Master":"积分至尊",
"ExLow Credit":"信用极低",
"Low Credit":"信用偏低",
"Normal Credit":"信用普通",
"Good Credit":"信用优秀",
"Credit Master":"值得信赖",
"Initiate":"启蒙者",
"Novice":"信徒",
"Disciple":"探求者",
"Hunter":"巡猎者",
"Eagle":"苍鹰",
"Tiger":"猎虎",
"Dragon":"天龙",
"Sage":"圣者",
"Master":"大师",
"Grand Master":"宗师",
"Internal Man":"内测者",
"UWP Player":"UWP玩家",
"WEB Player":"WEB玩家",
"Founder":"创始人",
"Baro Wallpaper":"KI'TEER 室内壁纸",
"Corpus Razorback Project":"利刃豺狼舰队",
"Ghoul Purge":"尸鬼入侵",
"Gifts Of The Lotus - Stolen!":"Lotus的礼物 - 失窃!",
"Plague Star":"瘟疫之星",
"Balor Fomorian":"巨人战舰",
"Tac Alert Proxy Rebellion":"机械叛乱",
"Angst":"焦虑",
"Malice":"怨恨",
"Mania":"躁狂",
"Misery":"苦难",
"Torment":"折磨",
"Violence":"暴力",
"Colour Picker Twitch B Item A":"显赫 色板",
"Prisma Twin Gremlins Weapon":"棱晶 双子小精灵",
"REVENANT":"REVENANT",
"Phantasma":"幻离子",
"Relay Title":"烈焰计划（重建中继站）",
"Mirage Alternate Skin":"MIRAGE 不朽外观",
"Enveloping Cloud":"包覆游云",
"Accumulating Whipclaw":"蓄积长鞭",
"Conductor":"指挥家",
"Mending Splinters":"治愈玻片",
"ZYLOK":"席尔火枪",
"Primed Sure Footed":"顶天立地 PRIME",
"Primed Charged Shell":"充电弹头 PRIME",
"Taxon Desert-camo Skin":"塔克桑 沙漠迷彩外观",
"CHROMA PRIME":"CHROMA PRIME",
"Chroma Prime":"龙甲 PRIME",
"Gram Prime":"格拉姆 PRIME",
"Rubico Prime":"绝路 PRIME",
"Gara Chassis Blueprint":"GARA 机体蓝图",
"Credits Cache":"现金匣",
"Gara Systems Blueprint":"GARA 系统蓝图",
"Gara Neuroptics Blueprint":"Gara 头部神经光元蓝图",
"Revenant System Blueprint":"REVENANT 系统蓝图",
"Revenant Chassis Blueprint":"REVENANT 机体蓝图",
"Eidolon Lens Blueprint":"夜灵晶体 蓝图",
"Revenant Neuroptics Blueprint":"REVENANT 头部神经光元蓝图",
"Shimmering Blight":"飞光荒疫",
"Furax Wraith Gauntlet":"弗拉克斯 亡魂 拳套",
"Dark Sword Day Of The Dead Skin":"暗黑长剑 亡灵节外观",
"Harkonar Wraith Cloak":"哈库纳亡魂斗篷",
"Primed Expel Corpus":"驱逐CORPUS PRIME",
"Primed Expel Corrupted":"驱逐堕落者 PRIME",
"Primed Expel Grineer":"驱逐GRINEER PRIME",
"Primed Expel Infested":"驱逐INFESTED PRIME",
"Falcor":"猎鹰轮",
"Pupacyst":"毒囊骨茧",
"Paracesis":"心智之殁",
"Cautious Shot":"谨慎射击",
"Power Donation":"献出力量",
"Sharpshooter":"神射手",
"Vigorous Swap":"强力切换",
"Rolling Guard":"翻滚防护",
"Adaptation":"适应",
"Harkonar Wraith Arm Armor":"哈库纳亡魂臂甲",
"Hallowed Nightmares Tactical Alert":"战术警报-万圣噩梦",
"Hallowed Nightmares-Time Attack":"战术警报-万圣噩梦",
"Primed Quickdraw":"持续火力 PRIME",
"Harkonar Wraith Chestbuard":"哈库纳亡魂胸甲",
"GARUDA":"GARUDA",
"Nagantaka":"噬蛇弩",
"Battacor":"武使之力",
"Ocucor":"视使之触",
"Kreska":"直镐",
"Oxylus":"奥克绪罗斯",
"Harkonar Wraith Leg Armor":"哈库纳亡魂腿甲",
"Synth Deconstruct":"合成 解构",
"Synth Fiber":"合成 纤维",
"Synth Charge":"合成 充能",
"Synth Reflex":"合成 反射",
"Mecha Overdrive":"机甲 超载",
"Mecha Recharge":"机甲 充能",
"Mecha Pulse":"机甲 脉冲",
"Mecha Empowered":"机甲 强化",
"Tek Collateral":"技法 连带",
"Tek Enhance":"技法 强化",
"Tek Gravity":"技法 引力",
"Tek Assault":"技法 猛袭",
"Tombfinger":"墓指",
"Catchmoon":"捕月",
"Gaze":"凝目",
"Rattleguts":"响胆",
"Elixis Tigris":"猛虎 镀铜外观",
"Avatar Image Glyph Cookie Kavat":"饼干库娃浮印",
"Avatar Image Glyph Cookie Kubrow":"饼干库狛浮印",
"Training Debt-Bond":"培训债务债券",
"Shelter Debt-Bond":"庇护债务债券",
"Medical Debt-Bond":"医疗债务债券",
"Thermal Sludge":"热能软泥",
"Tepa Nodule":"缇帕瘤",
"Familial Debt-Bond":"家族债务债券",
"Smooth Phasmin":"光滑翡斯敏石",
"Travoride":"铁镍矿",
"Travocyte Alloy":"铁镍合金",
"Phasmin":"翡斯敏石",
"Noctrul":"夜石",
"Heart Noctrul":"心形夜石",
"Axidite":"酸化矿物",
"Axidrol Alloy":"酸化合金",
"Goblite":"填充细石",
"Goblite Tears":"泪滴形填充细石",
"Venerol":"启明矿石",
"Venerdo Alloy":"启明合金",
"Amarast":"紫苋石",
"Star Amarast":"星形紫苋石",
"Hesperon":"长庚矿石",
"Hespazym Alloy":"长庚合金",
"Zodian":"黄道宝石",
"Radiant Zodian":"发光的黄道宝石",
"Thyst":"赤色水晶",
"Marquise Thyst":"女侯爵赤色水晶",
"Orb Vallis":"奥布山谷",
"Sapcaddy":"液集者",
"Echowinder":"回声环绕者",
"Brickie":"砖瓦匠",
"Scrubber":"洗涤者",
"Tink":"修补机",
"Eye-Eye":"目-目",
"Kriller":"磷虾杀手",
"Mirewinder":"污泥环绕者",
"Longwinder":"长型环绕者",
"Charamote":"重筑虾",
"Tromyzon":"多目鳗",
"Synathid":"海龙",
"Exa Brain":"艾脑",
"Venedo Case":"维内多箱",
"Scrap":"废料",
"Dissipator Coil":"消散线圈",
"Parallel Biode":"并联生物二极体",
"Rotoblade":"旋叶片",
"Muon Battery":"缪子电池",
"Neural Relay":"神经中继器",
"Entroplasma":"熵离子体",
"Anoscopic Sensor":"微孔视觉感应器",
"Thermal Laser":"热能激光",
"Lathe Coogulant":"车床凝冻液",
"Sagan Module":"萨根模块",
"Ecosynth Analyzer":"环境合成分析器",
"Mytocardia Spore":"心肌菌孢子",
"Gorgaricus Spore":"葛嘉里菌孢子",
"Sprint Boost":"冲刺提升",
"Mesa Prime":"MESA PRIME",
"Akjagara Prime":"觉醒双枪 PRIME",
"Redeemer Prime":"救赎者 PRIME",
"Kubrow Armor Prisma":"棱晶 洛斯塔姆库狛护甲",
"Ki'teer Cornu Diadem":"KI'TEER 角形头冠",
"Hypothermic Shell":"低温外壳",
"Charged Bullets":"带电子弹",
"Contamination Casing":"毒染套管",
"Infectious Injection":"传染性注射",
"Cryo Coating":"冷冻包覆",
"Ion Infusion":"离子注入",
"Sabot Rounds":"覆壳弹药",
"Critical Focus":"关键焦点",
"Exergis":"晶能放射器",
"Plinx":"漫射者",
"Galvacord":"电流刺索",
"Arch-Gun Ace":"Arch-枪械行家",
"Liset Cydonia Skin":"LISET 塞冬尼亚外观",
"Marked Target":"标记目标",
"Lith O1":"古纪 O1",
"Prisma Kavat Glyph":"棱晶 库娃浮印",
"Prisma Kubrow Glyph":"棱晶 库狛浮印",
"Arcane Scorpion Ash Helmet":"ASH 毒蝎秘奥头盔",
"Arcane Locust Ash Helmet":"ASH 飞蝗秘奥头盔",
"Arcane Reverb Banshee Helmet":"BANSHEE 返响秘奥头盔",
"Arcane Chorus Banshee Helmet":"BANSHEE 合音秘奥头盔",
"Arcane Phoenix Ember Helmet":"EMBER 凤凰秘奥头盔",
"Arcane Backdraft Ember Helmet":"EMBER 复燃秘奥头盔",
"Arcane Avalon Excalibur Helmet":"EXCALIBUR 阿瓦隆秘奥头盔",
"Arcane Pendragon Excalibur Helmet":"EXCALIBUR 潘德拉冈秘奥头盔",
"Arcane Aurora Frost Helmet":"FROST 极光秘奥头盔",
"Arcane Squall Frost Helmet":"FROST 飑风秘奥头盔",
"Arcane Essence Loki Helmet":"LOKI 本质秘奥头盔",
"Arcane Swindle Loki Helmet":"LOKI 诈欺秘奥头盔",
"Arcane Coil Mag Helmet":"MAG 线圈秘奥头盔",
"Arcane Gauss Mag Helmet":"MAG 高斯秘奥头盔",
"Arcane Flux Nova Helmet":"NOVA 通量秘奥头盔",
"Arcane Menticide Nyx Helmet":"NYX 灭神秘奥头盔",
"Arcane Vespa Nyx Helmet":"NYX 黄蜂秘奥头盔",
"Arcane Thrak Rhino Helmet":"RHINO 震击秘奥头盔",
"Arcane Vanguard Rhino Helmet":"RHINO 先锋秘奥头盔",
"Arcane Hemlock Saryn Helmet":"SARYN 铁杉秘奥头盔",
"Arcane Chlora Saryn Helmet":"SARYN 氯毒秘奥头盔",
"Arcane Aura Trinity Helmet":"TRINITY 预言秘奥头盔",
"Arcane Meridian Trinity Helmet":"TRINITY 经络秘奥头盔",
"Arcane Gambit Vauban Helmet":"VAUBAN 策略秘奥头盔",
"Arcane Storm Volt Helmet":"VOLT 风暴秘奥头盔",
"Arcane Pulse Volt Helmet":"VOLT 脉冲秘奥头盔",
"Orokin Catalyst Blueprint":"OROKIN催化剂 蓝图",
"Orokin Reactor Blueprint":"OROKIN反应堆 蓝图",
"Forma Blueprint":"FORMA 蓝图",
"Vauban Neuroptics Blueprint":"VAUBAN 头部蓝图",
"Vauban Chassis Blueprint":"VAUBAN 机体蓝图",
"Vauban Systems Blueprint":"VAUBAN 系统蓝图",
"Nidus Prion Helmet Blueprint":"NIDUS 朊毒头盔",
"Frost Squall Helmet Blueprint":"FROST 飑风头盔",
"Banshee Reverb Helmet Blueprint":"BANSHEE 返响头盔",
"Valkyr Kara Helmet Blueprint":"VALKYR 狂者头盔",
"Ember Backdraft Helmet Blueprint":"EMBER 复燃头盔",
"Loki Essence Helmet Blueprint":"LOKI 本质头盔",
"Mag Coil Helmet Blueprint":"MAG 线圈头盔",
"Trinity Meridian Helmet Blueprint":"TRINITY 经络头盔",
"Octavia Cadenza Helmet Blueprint":"OCTAVIA 华彩乐章头盔",
"Frost Aurora Helmet Blueprint":"FROST 极光头盔",
"Atlas Shikoro Helmet Blueprint":"ATLAS 兜围头盔",
"Volt Storm Helmet Blueprint":"VOLT 风暴头盔",
"Saryn Hemlock Helmet Blueprint":"SARYN 铁杉头盔",
"Nyx Menticide Helmet Blueprint":"NYX 灭神头盔",
"Banshee Chorus Helmet Blueprint":"BANSHEE 合音头盔",
"Hydroid Ketos Helmet Blueprint":"HYDROID 海怪头盔",
"Chroma Drac Helmet Blueprint":"CHROMA 龙蛇头盔",
"Ember Phoenix Helmet Blueprint":"EMBER 凤凰头盔",
"Valkyr Bastet Helmet Blueprint":"VALKYR 芭丝特头盔",
"Nova Flux Helmet Blueprint":"NOVA 通量头盔",
"Ash Scorpion Helmet Blueprint":"ASH 毒蝎头盔",
"Mag Gauss Helmet Blueprint":"MAG 高斯头盔",
"Volt Pulse Helmet Blueprint":"VOLT 脉冲头盔",
"Chroma Amaru Helmet Blueprint":"CHROMA 羽蛇神头盔",
"Limbo Magrite Helmet Blueprint":"LIMBO 画家头盔",
"Limbo Aristeas Helmet Blueprint":"LIMBO 诗人头盔",
"Nyx Vespa Helmet Blueprint":"NYX 黄蜂头盔",
"Atlas Tartarus Helmet Blueprint":"ATLAS 炼狱头盔",
"Hydroid Triton Helmet Blueprint":"HYDROID 海之信使头盔",
"Ash Locust Helmet Blueprint":"ASH 飞蝗头盔",
"Rhino Thrak Helmet Blueprint":"RHINO 震击头盔",
"Rhino Vanguard Helmet Blueprint":"RHINO 先锋头盔",
"Ivara Zirastra Helmet Blueprint":"IVARA 头罩头盔",
"Ivara Loxley Helmet Blueprint":"IVARA 洛克斯利头盔",
"Wukong Dasheng Helmet Blueprint":"WUKONG 大圣头盔",
"Wukong Macak Helmet Blueprint":"WUKONG 猕猴头盔",
"Equinox Solstice Helmet Blueprint":"EQUINOX 至点头盔",
"Excalibur Pendragon Helmet Blueprint":"EXCALIBUR 潘德拉冈头盔",
"Excalibur Mordred Helmet Blueprint":"EXCALIBUR 莫德雷头盔",
"Excalibur Avalon Helmet Blueprint":"EXCALIBUR 阿瓦隆头盔",
"Gara Virago Helmet Blueprint":"GARA 悍妇头盔",
"Inaros Anubis Helmet Blueprint":"INAROS 阿努比斯头盔",
"Inaros Canopic Helmet Blueprint":"INAROS 卡诺比斯头盔",
"Loki Enigma Helmet Blueprint":"LOKI 谜样头盔",
"Loki Swindle Helmet Blueprint":"LOKI 诈欺头盔",
"Mesa Longhorn Helmet Blueprint":"MESA 长角头盔",
"Mesa Ovis Helmet Blueprint":"MESA 角羊头盔",
"Mirage Harlequin Helmet Blueprint":"MIRAGE 丑角头盔",
"Mirage Trivelin Helmet Blueprint":"MIRAGE 丑仆头盔",
"Nekros Raknis Helmet Blueprint":"NEKROS 古墓头盔",
"Nekros Shroud Helmet Blueprint":"NEKROS 裹尸布头盔",
"Nezha Circa Helmet Blueprint":"NEZHA 奇尔卡头盔",
"Nova Quantum Helmet Blueprint":"NOVA 量子头盔",
"Nova Slipstream Helmet Blueprint":"NOVA 气流头盔",
"Oberon Markhor Helmet Blueprint":"OBERON 捻角山羊头盔",
"Oberon Oryx Helmet Blueprint":"OBERON 羚羊头盔",
"Saryn Chlora Helmet Blueprint":"SARYN 氯毒头盔",
"Titania Aurai Helmet Blueprint":"TITANIA 风之妖精头盔",
"Trinity Aura Helmet Blueprint":"TRINITY 预言头盔",
"Vauban Armistice Helmet Blueprint":"VAUBAN 休战头盔",
"Vauban Chapelon Helmet Blueprint":"VAUBAN 沙佩隆头盔",
"Vauban Esprit Helmet Blueprint":"VAUBAN 机敏头盔",
"Vauban Gambit Helmet Blueprint":"VAUBAN 策略头盔",
"Zephyr Cierzo Helmet Blueprint":"ZEPHYR 西熟风头盔",
"Zephyr Tengu Helmet Blueprint":"ZEPHYR 天狗头盔",
"Harrow Suffragan Helmet Blueprint":"HARROW 副主教头盔",
"Brokk Hammer Skin Blueprint":"重击巨锤 布洛克外观",
"Dagger Zoren Skin Blueprint":"佐轮双斧 戈刃外观",
"Scindo Manticore Axe Skin Blueprint":"分裂斩斧 蝎尾狮外观",
"Jaw Sword Blueprint":"蛇颚刀 蓝图",
"Ceramic Dagger Blueprint":"陶瓷匕首 蓝图",
"Dark Dagger Blueprint":"暗黑匕首 蓝图",
"Dark Sword Blueprint":"暗黑长剑 蓝图",
"Glaive Blueprint":"战刃 蓝图",
"Heat Dagger Blueprint":"烈焰短剑 蓝图",
"Heat Sword Blueprint":"烈焰长剑 蓝图",
"Pangolin Sword Blueprint":"鲮鲤剑 蓝图",
"Plasma Sword Blueprint":"等离子长剑 蓝图",
"Nezha JinZa Helmet Blueprint":"NEZHA 金吒头盔",
"Khora Delphi Helmet Blueprint":"KHORA 德尔菲头盔",
"Forma":"Forma",
"Equinox Clisthert Helmet Blueprint":"EQUINOX 晨昏恶魔头盔",
"Veiled Melee Riven Mod":"近战 裂罅MOD",
"Pistol Riven Mod":"手枪 裂罅MOD",
"Shotgun Riven Mod":"霰弹枪 裂罅MOD",
"Garuda Bathory Helmet Blueprint":"GARUDA 巴托里头盔",
"Revenant Vania Helmet Blueprint":"REVENANT 瓦尼亚头盔",
"Baruuk Meroe Helmet Blueprint":"Baruuk 麦罗埃头盔",
"Exilus Adapter Blueprint":"特殊功能槽连接器 蓝图",
"Enemy Physical Enhancement: Impact":"敌人物理强化：冲击",
"Enemy Physical Enhancement: Slash":"敌人物理强化：切割",
"Enemy Physical Enhancement: Puncture":"敌人物理强化：穿刺",
"Enemy Elemental Enhancement: Magnetic":"敌人元素强化：磁力",
"Enemy Elemental Enhancement: Corrosive":"敌人元素强化：腐蚀",
"Enemy Elemental Enhancement: Viral":"敌人元素强化：病毒",
"Enemy Elemental Enhancement: Electricity":"敌人元素强化：电击",
"Enemy Elemental Enhancement: Radiation":"敌人元素强化：辐射",
"Enemy Elemental Enhancement: Gas":"敌人元素强化：毒气",
"Enemy Elemental Enhancement: Heat":"敌人元素强化：火焰",
"Enemy Elemental Enhancement: Blast":"敌人元素强化：爆炸",
"Enemy Elemental Enhancement: Cold":"敌人元素强化：冰冻",
"Enemy Elemental Enhancement: Toxin":"敌人元素强化：毒素",
"Environmental Hazard: Radiation Pockets":"环境改变：辐射灾害",
"Environmental Hazard: Electromagnetic Anomalies":"环境改变：电磁异常",
"Environmental Hazard: Dense Fog":"环境改变：浓雾",
"Environmental Hazard: Fire":"环境改变：火灾",
"Environmental Effect: Cryogenic Leakage":"环境改变：冷却液泄漏",
"Weapon Restriction: Pistol Only":"武器限定：手枪",
"Weapon Restriction: Shotgun Only":"武器限定：霰弹枪",
"Weapon Restriction: Sniper Only":"武器限定：狙击枪",
"Weapon Restriction: Assault Rifle Only":"武器限定：突击步枪",
"Weapon Restriction: Melee Only":"武器限定：近战",
"Weapon Restriction: Bow Only":"武器限定：弓箭",
"Environmental Effect: Extreme Cold":"环境改变：极寒"}

export default messages;